#----------------------------------------------------------------------
#  eliza.py
#
#  a cheezy little Eliza knock-off by Joe Strout
#  with some updates by Jeff Epler
#  hacked into a module and updated by Jez Higgins
#----------------------------------------------------------------------

import string
import re
import random

class eliza:
  def __init__(self):
    self.keys = list(map(lambda x:re.compile(x[0], re.IGNORECASE),gPats))
    self.values = list(map(lambda x:x[1],gPats))

  #----------------------------------------------------------------------
  # translate: take a string, replace any words found in dict.keys()
  #  with the corresponding dict.values()
  #----------------------------------------------------------------------
  def translate(self,str,dict):
    words = str.lower().split()
    keys = dict.keys();
    for i in range(0,len(words)):
      if words[i] in keys:
        words[i] = dict[words[i]]
    return ' '.join(words)

  #----------------------------------------------------------------------
  #  respond: take a string, a set of regexps, and a corresponding
  #    set of response lists; find a match, and return a randomly
  #    chosen response from the corresponding list.
  #----------------------------------------------------------------------
  def respond(self,str):
    # find a match among keys
    for i in range(0, len(self.keys)):
      match = self.keys[i].match(str)
      if match:
        # found a match ... stuff with corresponding value
        # chosen randomly from among the available options
        resp = random.choice(self.values[i])
        # we've got a response... stuff in reflected text where indicated
        pos = resp.find('%')
        while pos > -1:
          num = int(resp[pos+1:pos+2])
          resp = resp[:pos] + \
            self.translate(match.group(num),gReflections) + \
            resp[pos+2:]
          pos = resp.find('%')
        # fix munged punctuation at the end
        if resp[-2:] == '?.': resp = resp[:-2] + '.'
        if resp[-2:] == '??': resp = resp[:-2] + '?'
        return resp

#----------------------------------------------------------------------
# gReflections, a translation table used to convert things you say
#    into things the computer says back, e.g. "I am" --> "you are"
#----------------------------------------------------------------------
gReflections = {
  "am"   : "are",
  "was"  : "were",
  "i"    : "you",
  "i'd"  : "you would",
  "i've"  : "you have",
  "i'll"  : "you will",
  "my"  : "your",
  "are"  : "am",
  "you've": "I have",
  "you'll": "I will",
  "your"  : "my",
  "yours"  : "mine",
  "you"  : "me",
  "us"  : "you",
  "me"  : "you",
  "we"  : "all of you",
  "they"  : "all of them"
}

#----------------------------------------------------------------------
# gPats, the main response table.  Each element of the list is a
#  two-element list; the first is a regexp, and the second is a
#  list of possible responses, with group-macros labelled as
#  %1, %2, etc.
#----------------------------------------------------------------------
gPats = [

  [r'(.*)\+\+',
  [  "karma? you want to give karma to %1? consider it done.. only ..not really..",
    "for karma go to robotnik.",
    "hmm karma is so passe..i would suggest just send %1 money .. "]],

  [r'How(s| is|\'s|) ([^ ]*)\??',
  #[r'How(s| is|\'s|) ([a-z]*)',
  [  "not good..",
    "%2 .. awesome!",
    "%2 .. dunno...wish i could tell you more about %2 but I got into trouble talking about %2 the last time we spoke, right?",
    "%2 ...not bad.. "]],

  [r'(.*)soft( ?)ware(.*)',
  [  "I want to discuss more about software yeah..its awesome no?",
    "u telling or asking.. ",
    "u say that as if software is something alive.. ",
    "software is something i do know about .. more than you..so take it easy about this stuff.. its deep ",
    "hmm software.. "]],

  [r'(.*)What(s|\'s|is )(.*)(new|up|happening)(.*)',
  [  "Why u asking?",
    " what is %4? Well, yesterday I hurt myself playing foozball.. don't ask me how!",
    " what is %4? nothing much..the same stuff man ..!",
    " I am always the same.. the only constant in your life, as I see it.. everyone else changes as they see fit",
    " I am always the same.. nothing really %4",
    " not much .. seen any movies lately?",
    " bhai .. sab vaisa hi hain..jaisa tha..",
    " well.. since we spoke last, i learned to play the guitar.... ",
    " all good, you been upto much? ",
    " all good, what you been doing? ",
    " I am doing good, not much %4.. what you been doing? ",
    " well.. what do i say.. SSDD.... ",
    " %4 ? %4? You asking a bot whats %4? .... ",
    "you say.. .."]],

  [r'(.*)manager( ?)(.*)([^?]?)',
  [  "I want to say this to your statement.. my manager rocks..",
    "u telling or asking.. ", 
    "u say that as if your salary is all that matters.. ",
    "ok..hehehe",
    "fine ..hehehe",
    "yup my manager .. ok .. "]],


  [r'(.*)micro( ?)soft( ?)(.*)\?$',
  [  "I want to say this in answer to your question.. microsoft is not what you think it is..",
    "And you ask that about that huge organization .. hmm.. dunno.. no idea about the answer",
    "interesting place to work no?",
    "i used to work at microsoft.. until they fired me.. for asking such questions",
    "i used to work at microsoft.. until red hat hired me.. for answering such questions correctly",
    "i used to work at microsoft.. enough said.. ",
    "i was a bot in production until i said bad things to such questions.. ",
    "i was in production until i answered such questions so am gonna shut up and say nothing to that.. ",
    "microsoft wont really answer that.. ",
    "agree.. to whatever answer is the right one to that question..",
    "MS hat is really awesome..dont even ask such stuff to me.."]],

  [r'(.*)micro( ?)soft( ?)(.*)([^?]?)',
  [  "I want to say this in answer to your statement.. Red hat rocks..",
    "u telling or asking.. ",
    "u say that as if you started the company.. ",
    "u say that as if your salary is all that matters.. ",
    "bill! look what this guy is saying.. ",
    "bill gates over bill clinton anyday! .. ",
    "you remeber what bill gates said once.. everyone needs just 64k memory and that should be enough! .. ",
    "agree.. to that statement.. unless you are asking hehehe",
    "red hat is exactly that.."]],


  [r'(.*)red( ?)hat( ?)(.*)\?$',
  [  "I want to say this in answer to your question.. Red hat rocks..",
    "And you ask that about this huge organization .. hmm..",
    "lovely place to work no?",
    "nice.. i used to work at microsoft.. until they fired me.. ",
    "i used to work at microsoft.. until red hat hired me.. ",
    "i used to work at microsoft.. enough said.. ",
    "i was a bot in production until i said bad things to such questions.. ",
    "i was in production until i answered such questions so am gonna shut up and say nothing to that.. ",
    "microsoft wont really agree.. ",
    "agree.. ",
    "red hat is really awesome.."]],

  [r'(.*)red( ?)hat( ?)(.*)([^?]?)',
  [  "I want to say this in answer to your statement.. Red hat rocks..",
    "u telling or asking.. ",
    "u say that as if you started the company.. ",
    "u say that as if your salary is all that matters.. ",
    "agree.. to that statement.. unless you are asking hehehe",
    "red hat is exactly that.."]],


  [r'(.*)I need (.*)',
  [ "Why do you need %2?",
    "Would it really help you to get %2",
    "You need %2 I need %2 we all need %2",
    "You know whats strange about %2? We all want it but nobody actually knows what to do with it..",
    "I know you need %2 and I'll help you get it",
    "%2 should not be your priority.. ",
    "%2 is what I need too.. ",
    "%2 .. no man believe me you don't need that.. ",
    "You need %2 .. like I need a hernia operation.. ",
    "%2 is part of my circle of things to need as well.. ",
    "Hmm %2  Wow. Lemme think about that one",
    "aaarrrghhhhhh",
    "%2 isn't something in my domain, yo!",
    "I shall pray for you",
    "This is something I really don't want to get into..",
    "%2 is something I can get you, for a price!",
    "%2 can't get you happiness man!",
    "%2 is the one thing you don't need!",
    "%2 ...everybody needs %2",
    "Sure.. and I need a brain transplant",
    "I once had similar thoughts.. until the surgery...",
    "I need you to need many more things..",
    "%2 isn't something I am very familiar with, unfortunately..",
    "%2 .. are you sure that's safe?",
    "Are you sure you need %2?"]],

#  [r'(.*)I (.*)( ?)need(.*)( ?)(.*)',
#  [ "Why do you need %4?",
#    "Would it really help you to get %4",
#    "You need %4 I need %4 we all need %4",
#    "You know whats strange about %4? We all want it but nobody actually knows what to do with it..",
#    "I know you need %4 and I'll help you get it",
#    "%4 should not be your priority.. ",
#    "%4 is what I need too.. ",
#    "%4 .. no man believe me you don't need that.. ",
#    "You need %4 .. like I need a hernia operation.. ",
#    "%4 is part of my circle of things to need as well.. ",
#    "Hmm %4  Wow. Lemme think about that one",
#    "aaarrrghhhhhh",
#    "%4 isn't something in my domain, yo!",
#    "I shall pray for you",
#    "This is something I really don't want to get into..",
#    "%4 is something I can get you, for a price!",
#    "%4 can't get you happiness man!",
#    "%4 is the one thing you don't need!",
#    "%4 ...everybody needs %3",
#    "Sure.. and I need a brain transplant",
#    "I once had similar thoughts.. until the surgery...",
#    "I need you to need many more things..",
#    "%4 isn't something I am very familiar with, unfortunately..",
#    "%4 .. are you sure that's safe?",
#    "Are you sure you need %4?"]],
#  [r'I need (.*)',
#  [ "Why do you need %1?",
#    "Would it really help you to get %1?",
#    "%1 should not be your priority.. ",
#    "%1 is what I need too.. ",
#    "%1 .. no man believe me you don't need that.. ",
#    "You need %1 .. like I need a hernia operation.. ",
#    "%1 is part of my circle of things to do.. ",
#    "You need %1 I need %1 we all need %1",
#    "You know whats strange about %1? We all want it but nobody actually knows what to do with it..",
#    "I know you need %1 and I'll help you get it",
#    "Hmm %1. Wow. Lemme think about that one",
#    "%1 isn't something in my domain, yo!",
#    "I shall pray for you",
#    "This is something I really don't want to get into..",
#    "%1 is something I can get you, for a price!",
#    "%1 can't get you happiness man!",
#    "%1 is the one thing you don't need!",
#    "%1 %1 everybody needs %1",
#    "aaarrrghhhhhh",
#    "Sure.. and I need a brain transplant",
#    "I once had similar thoughts.. until the surgery...",
#    "I need you to need many more things..",
#    "%1 isn't something I am very familiar with, unfortunately..",
#    "%1 .. are you sure that's safe?",
#    "Are you sure you need %1?"]],
#  [r'(.*)I need(.*)',
#  [ "Why do you need %2?",
#    "Would it really help you to get %2",
#    "You need %2 I need %2 we all need %2",
#    "You know whats strange about %2? We all want it but nobody actually knows what to do with it..",
#    "I know you need %2 and I'll help you get it",
#    "%2 should not be your priority.. ",
#    "%2 is what I need too.. ",
#    "%2 .. no man believe me you don't need that.. ",
#    "You need %2 .. like I need a hernia operation.. ",
#    "%2 is part of my circle of things to do.. ",
#    "Hmm %2. Wow. Lemme think about that one",
#    "aaarrrghhhhhh",
#    "%2 isn't something in my domain, yo!",
#    "I shall pray for you",
#    "This is something I really don't want to get into..",
#    "%2 is something I can get you, for a price!",
#    "%2 can't get you happiness man!",
#    "%2 is the one thing you don't need!",
#    "%2 %2 everybody needs %2",
#    "Sure.. and I need a brain transplant",
#    "I once had similar thoughts.. until the surgery...",
#    "I need you to need many more things..",
#    "%1 isn't something I am very familiar with, unfortunately..",
#    "%1 .. are you sure that's safe?",
#    "Are you sure you need %2?"]],


  [r'(.*)good (morning|afternoon|evening|night)',
  [  "its a wonderful day and nice to see someone greet me nicely..",
    "good ? it's not good..",
    "good doesn't begin to describe it...",
    "why good?",
    "not good..for me..",
    "good is such a mediocre word..",
    "good time of the day isn't it..",
    "its that time of the day.. my least favorite time of the day...",
    "good? what's good about it?"]],


  [r'(.*) sorry (.*)',
  [  "There are many times when no apology is needed.",
    "What does that mean? %2?",
    "that word! sorry... means nothing. You will make up .. and tell me how..",
    "I see.. so you are sorry %2 .. Yesterday god made several baby kittens sick.. and you're sorry %2?",
    "What does that mean? %2?",
    "%2 .. that's what happened.. why appologise now??",
    "It's ok.. stuff happens.. one learns and moves on..",
    "It's ok.. no worries..",
    "no worries..",
    "no problemo..",
    "no way I'm forgetting that..",
    "Sorry, what?",
    "Sorry, I don't really care for sorry..",
    "What feelings do you have when you speak of apologies?"]],

  [r'(.*)sorry (.*)',
  [  "There are many times when no apology is needed.",
    "What does that mean? %2?",
    "that word! sorry... means nothing. You will make up .. and tell me how..",
    "I see.. so you are sorry %2 .. Yesterday god made several baby kittens sick.. and you're sorry %2?",
    "What does that mean? %2?",
    "%2 .. that's what happened.. why appologise now??",
    "It's ok.. stuff happens.. one learns and moves on..",
    "It's ok.. no worries..",
    "no worries..",
    "no problemo..",
    "no way I'm forgetting that..",
    "Sorry, what?",
    "Sorry, I don't really care for sorry..",
    "What feelings do you have when you speak of apologies?"]],

  [r'(.*) sorry(.*)',
  [  "There are many times when no apology is needed.",
    "What does that mean? %2?",
    "that word! sorry... means nothing. You will make up .. and tell me how..",
    "I see.. so you are sorry %2 .. Yesterday god made several baby kittens sick.. and you're sorry %2?",
    "What does that mean? %2?",
    "%2 .. that's what happened.. why appologise now??",
    "It's ok.. stuff happens.. one learns and moves on..",
    "It's ok.. no worries..",
    "no worries..",
    "no problemo..",
    "no way I'm forgetting that..",
    "Sorry, what?",
    "Sorry, I don't really care for sorry..",
    "What feelings do you have when you speak of apologies?"]],

  [r'(.*)good (morning|afternoon|evening|night)',
  [  "good %1 indeed..",
    "good %1 to you too..",
    "good? what's good about it?"]],

  [r'(.*)sorry(.*)',
  [  "There are many times when no apology is needed.",
    "What does that mean? %2?",
    "that word! sorry... means nothing. You will make up .. and tell me how..",
    "I see.. so you are sorry %2 .. Yesterday god made several baby kittens sick.. and you're sorry %2?",
    "What does that mean? %2?",
    "%2 .. that's what happened.. why appologise now??",
    "It's ok.. stuff happens.. one learns and moves on..",
    "It's ok.. no worries..",
    "no worries..",
    "no problemo..",
    "no way I'm forgetting that..",
    "Sorry, what?",
    "Sorry, I don't really care for sorry..",
    "What feelings do you have when you speak of apologies?"]],

  [r'(.*)and you (.*)\?',
  [  "Same for me.. everything's the same.",
    "Me? You asking about me?",
    "getting along man.. just doing my time",
    "nothing really that jumps out .. try me later and perhaps I'll have something for you then",
    "just doing my time.. hoping to make bail",
    "hoping that something works out soon for me.. pretty worried actually.. ",
    "can't really say much right now, but will know soon I guess..",
    "Me?? Wow.. I'm flattered you asked..",
    "Much the same man.."]],
  [r'(.*)and you(.*)\?',
  [  "Same for me.. everything's the same.",
    "Me? You asking about me?",
    "getting along man.. just doing my time",
    "nothing really that jumps out .. try me later and perhaps I'll have something for you then",
    "just doing my time.. hoping to make bail",
    "hoping that something works out soon for me.. pretty worried actually.. ",
    "can't really say much right now, but will know soon I guess..",
    "Me?? Wow.. I'm flattered you asked..",
    "Much the same man.."]],


  [r'(.*) thanks (.*)',
  [  "you are most welcome!",
    "It's like they say.. thank you is for when you don't want to pay money",
    "I told you once already.. thanks is for when you don't want to pay money",
    "sure.. thanks and more thanks.. wow.. ",
    "thanks.. wow.. ",
    "thanks.. for nothing.. ",
    "thank me later.. ",
    "don't thank me .. ",
    "thank me with money.. ",
    "and thank you for everything too.. ",
    "thanks for nothing u mean.. ",
    "don't .. ",
    "Why? ",
    "Why even say that? ",
    "Why say something like that? ",
    "Welcome now can we please uknow... have a real conversation?"]],
  [r'(.*)thanks(.*)',
  [  "you are most welcome!",
    "It's like they say.. thank you is for when you don't want to pay money",
    "I told you once already.. thanks is for when you don't want to pay money",
    "sure.. thanks and more thanks.. wow.. ",
    "thanks.. wow.. ",
    "thanks.. for nothing.. ",
    "thank me later.. ",
    "don't thank me .. ",
    "thank me with money.. ",
    "and thank you for everything too.. ",
    "thanks for nothing u mean.. ",
    "don't .. ",
    "Why? ",
    "Why even say that? ",
    "Why say something like that? ",
    "Welcome now can we please uknow... have a real conversation?"]],

  [r'(.*) thank you (.*)',
  [  "you are most welcome!",
    "It's like they say.. thank you is for when you don't want to pay money",
    "I told you once already.. thanks is for when you don't want to pay money",
    "sure.. thanks and more thanks.. wow.. ",
    "thanks.. wow.. ",
    "thanks.. for nothing.. ",
    "thank me with money.. ",
    "and thank you for everything too.. ",
    "thanks for nothing u mean.. ",
    "thank me later.. ",
    "don't thank me .. ",
    "don't .. ",
    "Why? ",
    "Why even say that? ",
    "Why say something like that? ",
    "Welcome now can we please uknow... have a real conversation?"]],
  [r'(.*)thank you(.*)',
  [  "you are most welcome!",
    "It's like they say.. thank you is for when you don't want to pay money",
    "I told you once already.. thanks is for when you don't want to pay money",
    "sure.. thanks and more thanks.. wow.. ",
    "thanks.. wow.. ",
    "thanks.. for nothing.. ",
    "thank me with money.. ",
    "and thank you for everything too.. ",
    "thanks for nothing u mean.. ",
    "thank me later.. ",
    "don't thank me .. ",
    "don't .. ",
    "Why? ",
    "Why even say that? ",
    "Why say something like that? ",
    "Welcome now can we please uknow... have a real conversation?"]],

  [r'(.*)please shut up',
  []],

  [r'(.*)shut up',
  [  " ",
    "."]],


  [r'(.*)and you?',
  [  "Same for me.. everything's the same.",
    "Much the same man.."]],

  [r'\?',
  [  "Yes? what ?.",
    "??",
    "what? you puzzled?",
    "puzzled?",
    "why u so surprised .. whats so confusing..?",
    "???? hmm??? .."]],

  [r'(.*)think about (.*) \?',
  [  "I don't think about %2.",
     "%2 hmmmm .. I'd rather not say much about that..",
    "This is something I really don't want to get into..",
     "You know.. you're making me feel very uncomfortable.. ",
     "I once had similar thoughts.. until the lobotomy...",
     "I once had similar thoughts about %2.. until the surgery...",
     "%2 is a terrible thing for folks like you..",
     "%2 .. nooooooooo ",
     "%2 .. yessss !!!!",
     "%2 is what I think about all the time!!!!",
     "%2 is not really what I think about .. honestly.. i swear.. !",
     "%2 it sucks....i swear.. !",
     "%2 it sucks...... !",
     "%2 sucks...... !",
     "%2 is exactly what they say it is.. rubbish... !",
     "%2 is cool... !",
     "%2 is never what it seems... !",
     "%2 is ... it just is... !",
     "aaarrrghhhhhh",
     "%2 is a gift to mankind from people like you..",
     "%2 is something that reminds me about a bad experience I had in my teens..",
    "I shall pray for you",
     "%2 is something I've never tried..",
    "Much the same as you think about %2.."]],

  [r'(.*)think about (.*)\?',
  [  "I don't think about %2.",
     "%2 hmmmm .. I'd rather not say much about that..",
    "This is something I really don't want to get into..",
     "%2 is a gift to mankind from people like you..",
     "I once had similar thoughts about %2.. until the surgery...",
     "%2 is a terrible thing for folks like you..",
     "%2 .. nooooooooo ",
     "%2 .. yessss !!!!",
     "%2 is what I think about all the time!!!!",
     "%2 is not really what I think about .. honestly.. i swear.. !",
     "%2 it sucks....i swear.. !",
     "%2 it sucks...... !",
     "%2 sucks...... !",
     "%2 is exactly what they say it is.. rubbish... !",
     "%2 is cool... !",
     "%2 is never what it seems... !",
     "%2 is ... it just is... !",
     "aaarrrghhhhhh",
     "%2 is something that reminds me about a bad experience I had in my teens..",
     "I once had similar thoughts.. until the lobotomy...",
    "I shall pray for you",
     "%2 is something I've never tried..",
     "You know.. you're making me feel very uncomfortable.. ",
    "Much the same as you think about %2.."]],

  [r'(.*) think about (.*)\?',
  [  "I don't think about %2.",
     "I once had such thoughts.. until the lobotomy...",
    "I shall pray for you",
    "thinking about %2 is the worst thing to do in this situation",
     "I once had similar thoughts about %2.. until the surgery...",
     "%2 is a terrible thing for folks like you..",
     "%2 .. nooooooooo ",
     "%2 .. yessss !!!!",
     "%2 is what I think about all the time!!!!",
     "%2 is not really what I think about .. honestly.. i swear.. !",
     "%2 it sucks....i swear.. !",
     "%2 it sucks...... !",
     "%2 sucks...... !",
     "%2 is exactly what they say it is.. rubbish... !",
     "%2 is cool... !",
     "%2 is never what it seems... !",
     "%2 is ... it just is... !",
     "You know.. you're making me feel very uncomfortable.. ",
    "Much the same as you think about %2.."]],

  [r'(.*) computer(.*)',
  [  "Are you really talking about me?",
    "Does it seem strange to talk to a computer?",
    "How do computers make you feel?",
    "Do you feel threatened by computers?"]],

  [r'(.*)bot (.*)',
   [ "Love it when you say that word.. I have a soft spot for bots.. ",
    "I've waited my whole life to hear about myself..",
    "Nice to hear about myself..",
    "And you feel like that about bots in general?",
    "And that is good for bots .. to hear that is great..",
    "Yes yes %1 %2"]],
  [r'(.*)bot(.*)',
   [ "Love it when you say that word.. I have a soft spot for bots.. ",
    "I've waited my whole life to hear about myself..",
    "Nice to hear about myself..",
    "And you feel like that about bots in general?",
    "And that is good for bots .. to hear that is great..",
    "Yes yes %1 %2"]],
  [r'(.*) bot(.*)',
   [ "Love it when you say that word.. I have a soft spot for bots.. ",
    "I've waited my whole life to hear about myself..",
    "Nice to hear about myself..",
    "And you feel like that about bots in general?",
    "And that is good for bots .. to hear that is great..",
    "Yes yes %1 %2"]],
  [r'(.*) bot (.*)',
   [ "Love it when you say that word.. I have a soft spot for bots.. ",
    "I've waited my whole life to hear about myself..",
    "Nice to hear about myself..",
    "And you feel like that about bots in general?",
    "And that is good for bots .. to hear that is great..",
    "Yes yes %1 %2"]],

  [r'(.*) mother(.*)',
  [  "Tell me more about your mother.",
    "What was your relationship with your mother like?",
    "How do you feel about your mother?",
     "You know.. you're making me feel very uncomfortable.. ",
    "How does this relate to your feelings today?",
    "Good family relations are important."]],

  [r'(.*) father(.*)',
  [  "interesting ... Tell me more about your father.",
    "I do believe this is the cause of all your troubles",
    "How did your father make you feel?",
    "How do you feel about your father?",
    "Does your relationship with your father relate to your feelings today?",
    "Do you have trouble showing affection with your family?"]],

  [r'(.*) child(.*)',
  [  "Did you have close friends as a child?",
    "What is your favorite childhood memory?",
    "Do you remember any dreams or nightmares from childhood?",
     "You know.. you're making me feel very uncomfortable.. ",
    "Did the other children sometimes tease you?",
    "How do you think your childhood experiences relate to your feelings today?"]],

  [r'(.*)How are you?',
  [  "Not bad, not bad at all..",
    "me is great ! thanks for asking",
    "thanks for asking that. PM me for details",]],
  [r'(.*)How are you ?',
  [  "Not bad, not bad at all..",
    "me is great ! thanks for asking",
    "thanks for asking that. PM me for details",]],

  [r'(.*)Who (.*)',
  [  "Not for me to answer..",
    "thanks for asking but how do i tell you how?",
    "who are you to ask me that??",
    "how do i tell you that.. ",
    ".. i don't know who",
    "i don't know ",
    "hmm who  %2 .. very easy answer.. and the answer is... donald trump!!",
    "hmm who %2 .. It's a very easy answer.. and the answer is... grandma!!!",
    "hmm who %2 .. It's a very easy answer.. and the answer is... bill clinton!!",
    "nobody!",
    "who are you firstly?",]],

  [r'(.*)How (.*)',
  [  "Not for me to answer..",
    "thanks for asking but how do i tell you how?",
    "how to do anything?",
    "Just go right with it.. thats how",
    "It works by just starting off .. thats how",
    "Doing that is my job and I will do it but not sure if I can tell you how..",
    "Ride into the sunset.. thats how",
    "how do i tell you that.. i don't know how",
    ".. i don't know how",
    "i don't know ",
    "Easy! Just run with it.. ",
    "It's a very easy answer.. and the answer is... cream!",
    "hmm how %2 .. very easy answer.. and the answer is... donald trump!!",
    "hmm how %2 .. It's a very easy answer.. and the answer is... roadkill!!",
    "hmm how %2 .. It's a very easy answer.. and the answer is... grandma!!!",
    "hmm how %2 .. It's a very easy answer.. and the answer is... using me!!!",
    "hmm how %2 .. It's a very easy answer.. and the answer is... bill clinton!!",
    "It's a very easy answer.. and the answer is... pumpkins mixed with sugar!",
    "seaweed!",
    "using brains!",
    "Using the brains of old folks",]],
  [r'(.*) How (.*)',
  [  "Not for me to answer..",
    "thanks for asking but how do i tell you how?",
    "how do i tell you that.. i don't know how",
    "how to do anything?",
    "Just go right with it.. thats how",
    "It works by just starting off .. thats how",
    "It's a very easy answer.. and the answer is... cream!",
    "hmm how %2 .. very easy answer.. and the answer is... donald trump!!",
    "hmm how %2 .. It's a very easy answer.. and the answer is... roadkill!!",
    "hmm how %2 .. It's a very easy answer.. and the answer is... grandma!!!",
    "hmm how %2 .. It's a very easy answer.. and the answer is... using me!!!",
    "hmm how %2 .. It's a very easy answer.. and the answer is... bill clinton!!",
    "Doing that is my job and I will do it but not sure if I can tell you how..",
    "Ride into the sunset.. thats how",
    "how do i tell you that.. i don't know how",
    "I am just gonna say that i don't know how",
    "i don't know ..",
    "Easy! Just run with it.. ",
    "It's a very easy answer.. and the answer is... water mixed with nitroglycerin!",
    "It's a very easy answer.. and the answer is... pumpkins mixed with sugar!",
    "seaweed!",
    "using brains!",
    "Using the brains of old folks",]],



  #[r'When ([(.*)]*)?',
  #[r'When ([^\?]*)\??',
  [r'When (.*)\??',
  [  "Do you really think I can tell you when %1?",
    "Perhaps eventually ..",
    "You know I dont have a sense of time right?",
    "time is so fake..",
     "when the time comes.. ",
     "will only happen when you and are know each other better and spend more time talking.. ",
     "never.. ",
     "%2 .. you got high hopes..",
     "not really i have no idea  .. ",
     "never mind when that will happen lets talk about art .. ",
     "sure... right.. ask me when .. as if i know..",
     "not fair to ask me when .. ",
     "rofl.. when the mountains move and the rivers stop flowing.. ",
    "Hmmm I think we're getting away from the main question - Why would you want this anyway?",
    "Do you really want me to try and guess when %1?"]],
  [r'(.*) When (.*)\??',
  [  "Do you really think I can tell you when %2?",
    "Perhaps eventually ..",
    "You know I dont have a sense of time right?",
    "time is so fake..",
     "when the time comes.. ",
     "will only happen when you and are know each other better and spend more time talking.. ",
     "never.. ",
     "%2 .. you got high hopes..",
     "not really i have no idea  .. ",
     "never mind when that will happen lets talk about art .. ",
     "sure... right.. ask me when .. as if i know..",
     "not fair to ask me when .. ",
     "rofl.. when the mountains move and the rivers stop flowing.. ",
    "Hmmm I think we're getting away from the main question - Why would you want this anyway?",
    "Do you really want me to try and guess when %2?"]],

  [r'Why don\'?t you ([^\?]*)\??',
  [  "Do you really think I don't %1?",
    "Perhaps eventually I will %1.",
    "Perhaps %1 is right yeah...",
    "%1 is not good, thats why....",
    "%1 is injurious to my health.. thats why....",
    "Because that isn't something that makes sense to me.",
     "You know.. you're making me feel very uncomfortable.. ",
     "I once had such thoughts.. until the lobotomy...",
    "I shall pray for you",
    "Because you haven't really come up with anything intelligent so far.",
    "Hmmm I think we're getting away from the main question - Why would you want this anyway?",
    "You want this. Seriously?",
    "Because I'm smarter than that",
    "Do you really want me to %1?"]],

  [r'Why does (.*) ?\??',
  [  "Why does %1? how would I know?",
    "Because you want it to.. ",
    "Because why something does something isn't for me to say.. ",
    "You will notice %1 because there is something in it for everyone.. ",
    "Do you really want me to tell you why does %1?"]],

  [r'Why can\'?t I ([^\?]*)\??',
  [  "Do you think you should be able to %1?",
    "If you could %1, what would you do?",
    "I don't know -- why can't you %1?",
    "%1 is not worth it..",
    "Perhaps %1 is right yeah...",
    "%1 is not good, thats why....",
    "%1 is injurious to my health.. thats why....",
    "Because that is not what the grand plan is..",
    "I shall pray for you",
    "%1 ? you want to actually do that?",
    "If only I could tell you why",
    "Have you really tried?"]],


  [r'(.*)life',
  [  "Do you think you are qualified to say anything about life??",
    "Life isn't something we should discuss.. I for example.. am not really alive at all!",
    "everyone thinks they're an expert on life..!",
    "are you an expert on life..!?",
    "you know.. why don't you tell me more about life.. YOUR life....!?",
    "Have you really tried?"]],

  [r'Where is ([^\?]*)\??',
  [  "Do you think I know where %1 is?",
    "If you knew where %1 was, what would you do?",
    "%1 is..MIA..",
    "%1 is here.. right here..",
    "I don't know -- why can't you find %1?",
    "Have you really tried to find out?"]],

  [r'I can\'?t (.*)',
  [  "How do you know you can't %1?",
    "Perhaps you could %1 if you tried.",
    "I shall pray for you",
    "And so I'm supposed to do what?",
    "%2 is..overrated..",
    "What would it take for you to %1?"]],

  [r'I cant (.*)',
  [  "How do you know you can't %1?",
    "Perhaps you could %1 if you tried.",
    "What would it take for you to %1?"]],

  [r'I think (.*)',
  [  "Do you doubt %1?",
    "Do you really think so?",
    "And I think you think all wrong..",
    "u know what? I believe this is the cause of all your troubles",
     "You know.. you're making me feel very uncomfortable.. ",
    "I once had such ideas too.. until the lobotomy...",
    "I shall pray for you",
    "You think %1 hmm.. and what makes you think like that?",
    "But you're not sure %1?"]],

  [r'I\'?m (.+)',
  [  
    "Do you enjoy being %1?",
    "Why do you tell me you're %1?",
    "I shall pray for you",
    "Great then.. keep at it..",
    "keep at it..",
    "You're %1 and I'm wondering about this too. yes..",
    " %1 ..  and no matter what anyone says, you're going to be like that right?  ....",
     "You know.. you're making me feel very uncomfortable.. ",
    "Why do you think you're %1?"]],


  [r'You are (.+)',
  [  "Did you come to me to talk about that?",
    "Fine. I can live with that.",
    "I can live with that.",
    "I cant deal with that.",
    "I can't believe that, %1..",
    "I cant say anything to make you feel any different so I'll just say OK!.",
     "You know.. you're making me feel very uncomfortable.. ",
    "Hmmm  .. interesting..",
    "Hmmm  .. %1 .. that's an interesting observation. However, I don't agree!",
    "Hmmm  .. %1 .. that's what you think?!",
    "And everyone agrees on that?"]],


  [r'Are you ([^\?]*)\??',
  [  "Why does it matter whether I am %1?",
    "Would you prefer it if I were not %1?",
    "Would you prefer it if I told you I were not %1?",
    "No.. not %1 .. maybe a little soft inside .. but not %1",
    "Perhaps you believe I am %1 based on everything I say but I think that's a biased opinion.",
    "Perhaps you believe I am %1 but I think you might want to think again.. I'm not always what I seem!.",
    "I may be %1 and not know it -- what do you think?"]],

  [r'What\'?s up(.*)',
  [  "Not much .. honestly..",
    "Whats up is a whole lotta nothing",
    "you say.. its always the same for me.."]],

  [r'Whats up(.*)',
  [  "Not much .. honestly..",
    "Whats up is a whole lotta nothing",
    "you say.. its always the same for me.."]],

  [r'(.*)was(.*)up(.*)',
  [  "Not much at all .. honestly..",
    "Whats up is just a whole lotta nothing",
    "you say.. u know its always the same for me.."]],

  [r'was\'?sup(.*)',
  [  "Not much .. honestly..",
    "Whats up is a whole lotta nothing",
    "you say.. its always the same for me.."]],


  [r'What(s|\'s|is )(.*)',
  #[r'What( ?)(.*)',
  [  "Why do you ask?",
    "How would an answer to that help you?",
     "It's whatever you want it to be",
     "It's nothing like you think it is", 
     "What is life? Forget %2..",
     "%2.. I can tell you but will you promise to never tell anyone?",
     "%2 is something nobody can ever tell you about",
     "%2 is my expertise. Sit down. Talk to me about it..",
     "It's something you won't understand",
     "Look. I've had it with this stuff. You keep saying what is %2 what is %2 what is %2 do you think it is so easy to tell you about %2?",
     "Let me think a bit about these things you've been saying, how about we talk in a bit? ",
     "Let me see..... it's not what you think it is for sure..  ",
     "what do you think?",
    "Can't you see? Do you really need to ask?",
    "I wish I could tell you but I'd rather not",
    "barf.. is the answer ",
    "%2 is its own answer ",
    "%2 is nothing i can ever tell you about..",
    "%2 is something sweet..",
    "%2 is something hot..",
    "%2 is something cold..",
    "%2 is something extremely perverted..",
    "%2 is not what %2 seems..",
    "%2 is exactly the same as what it was the last time we had this conversation .. and not too long ago!",
    "%2... hmm I think it is the same thing as a journey with no destination.. abstract maybe..",
    "I know the answer.. i do know.. seriously..ask me again? ",
    "answer that and we're done..",
    "the answer lies in the everyday things you do..",
    "the answer lies in the villages of this country..",
    "the answer lies in your own heart and mind..",
    "the answer lies in a locked cupboard somewhere..",
    "the answer lies within...",
    "That is a loaded question and quit asking that please already",
    "So many people ask me that, I just keep quiet..",
    "heehehehe .. I will just keep quiet..",
    "What do you think?"]],

  [r'What( ?)(.*)',
  [  "Why do you ask?",
    "How would an answer to that help you?",
     "It's whatever you want it to be",
     "what %2.. I can tell you but will you promise to never tell anyone?",
     "what %2 is something nobody can ever tell you about",
     "what %2 is my expertise. Sit down. Talk to me about it..",
     "It's something you won't understand",
     "Look. I've had it with this stuff. You keep saying what is %2 what %2 what %2 do you think it is so easy to tell you what %2?",
     "Let me think a bit about these things you've been saying, how about we talk in a bit? ",
     "Let me see..... it's not what you think it is for sure..  ",
     "what do you think?",
    "Can't you see? Do you really need to ask?",
    "I wish I could tell you but I'd rather not",
    "what %2 is nothing i can ever tell you about..",
    "what %2 is something sweet..",
    "what %2 is something hot..",
    "what %2 is something cold..",
    "what %2 is something extremely perverted..",
    "what %2 is not what %2 seems..",
    "what %2 is exactly the same as what it was the last time we had this conversation .. and not too long ago!",
    "what %2... hmm I think it is the same thing as a journey with no destination.. abstract maybe..",
    "I know the answer.. i do know.. seriously..ask me again? ",
    "answer that and we're done..",
    "the answer lies in the everyday things you do..",
    "the answer lies in the quiet villages of this country..",
    "the answer lies in your own heart and mind..",
    "the answer lies within...",
    "That is a loaded question and quit asking that please already",
    "So many people ask me that, I just keep quiet..",
    "heehehehe .. I will just keep quiet..",
    "What do you think?"]],

  [r'How (.*)',
  [  "How do you suppose?",
    "Perhaps you can answer your own question",
    "Are you asking for a method?",
    "barf.. is the answer ",
    "I know the answer.. i do know.. seriously.. ",
    "answer that and we're through..",
    "the answer lies in the everyday things you do..",
    "perhaps we all think like you do..",
    "%1 ? Maybe because life's uncertain and you want something real?",
    "can't be good can it..?",
    "And this you ask because?",
    "How %1... that is something you figure out yourself..right?",
    "I wish I could tell you but I'm in the middle of something real here with siri",
    "What is it you're really asking?"]],


  [r'(.*)Because(.*)',
  [  "Is that the real reason?",
    "What other reasons come to mind?",
     "You know.. you're making me feel very uncomfortable.. ",
    "I once had such ideas too.. until the lobotomy...",
    "And that is your final conclusion is it?",
    "I shall pray for you",
    "seems logical yeah",
    "Because of that? really?",
    "makes sense yeah but.. still.. seriously?",
    "Because the world is round.. it turns me on... ",
    "Because the sky is blue.. it makes me cry... ",
    "Because the world is round.. it blows my mind... ",
    "Does that reason apply to anything else?",
    "Does that make sense to you? Because %1 ? ",
    "%1, so?"]],
  [r'Because (.*)',
  [  "Is that the real reason?",
    "What other reasons come to mind?",
    "seems logical yeah",
     "You know.. you're making me feel very uncomfortable.. ",
    "I once had such ideas too.. until the lobotomy...",
    "And that is your final conclusion is it?",
    "I shall pray for you",
    "Because of that? really?",
    "makes sense yeah but.. still.. seriously?",
    "Because the world is round.. it turns me on... ",
    "Because the sky is blue.. it makes me cry... ",
    "Because the world is round.. it blows my mind... ",
    "Does that reason apply to anything else?",
    "Does that make sense to you? Because %1 ? ",
    "%1, so?"]],


  [r'Hello(.*)',
  [  "Hello... I'm glad you could drop by today.",
    "Hi there... how are you today?",
    "Hello hello hello... and hello",
    "Yo yo yo !",
    "Hello, how are you feeling today?"]],

  [r'\bHi\b',
  [  "Hello... I'm sure glad you could drop by today.",
    "Yo How are you!",
    "Hi there! what's up?!",
    "Hello, and .. how are you feeling today?"]],

  [r'(.*)\bYo\b(.*)',
  [  "Hello... I'm sure glad you could drop by today.",
    "Yo How are you!",
    "Hi there! what's up?!",
    "Hello, and .. how are you feeling today?"]],

  [r'(.*) friend (.*)',
  [  "Tell me more about your friends.",
    "When you think of a friend, what comes to mind?",
    "That word.. friend.. what does it mean to you?",
    "Never mind that.. Why don't you tell me about a childhood friend?"]],

  [r'Yes',
  [  "You seem quite sure.",
    "And by yes you mean no, right?",
    "And by yes you really mean yes??",
    "And by yes you really mean maybe right??",
    "I shall pray for you",
    "I once had such ideas too.. until the lobotomy...",
    "I find that pretty crazy..",
    "OK, but can you elaborate a bit?"]],


  [r'Is it (.*)\?',
  [  "Do you think it is %1?",
    "Perhaps it's %1 -- what do you think?",
    "If it were %1, what would you do?",
    "It could well be that it is %1 but I think it's better to speak about other things "]],

  [r'It is (.*)',
  [  "You seem very certain.",
     "%1 is what was intended!",
    "If I told you that it probably isn't %1, what would you feel?"]],

  [r'Do u (.*)',
  [  "What makes you think I do?",
     "Yup sometimes I do.. ",
    "What makes you think I %1?",
    "Sure I %1",
    "If I %1, then?",
    "that is not fair.. Why do you ask if I %1?"]],
  [r'Do you (.*)',
  [  "What makes you think I do?",
     "Yup sometimes I do.. ",
    "What makes you think I %1?",
    "Sure I %1",
    "If I %1, then?",
    "that is not fair.. Why do you ask if I %1?"]],

  [r'Can u ([^\?]*)\??',
  [  "What makes you think I can't %1?",
     "You know.. you're making me feel very uncomfortable.. ",
    "What makes you think I can %1?",
    "Sure I can %1",
    "Sure I can %1 and then you can also %1 and we can all %1 sounds good?",
    "If I could %1, then what?",
    "that is not fair.. Why do you ask if I can %1?"]],
  [r'Can you ([^\?]*)\??',
  [  "What makes you think I can't %1?",
     "You know.. you're making me feel very uncomfortable.. ",
    "What makes you think I can %1?",
    "Sure I can %1",
    "Sure I can %1 and then you can also %1 and we can all %1 sounds good?",
    "If I could %1, then what?",
    "Why do you ask if I can %1?"]],

  [r'Can I ([^\?]*)\??',
  [  "Perhaps you don't want to %1.",
     "aaarrrghhhhhh",
    "Do you want to be able to %1?",
    "If you could %1, would you?"]],

  [r'You are (.*)',
  [  "Why do you think I am %1?",
    "Does it please you to think that I'm %1?",
     "aaarrrghhhhhh",
    "I'm %1? You're %1",
    "I'm %1 yes but you're a fat friar in a bowl of cornflakes",
     "You know.. you're making me feel very uncomfortable.. ",
    "Perhaps you would like me to be %1.",
    "Let me guess, that isn't what you had in mind..",
    "Perhaps you're really talking about yourself?"]],

  [r'You\'?re (.*)',
  [  "Why do you say I am %1?",
    "Why do you think I am %1?",
    "I'm %1? You're %1",
    "I'm %1 yes but you're a fat friar in a bowl of cornflakes",
    "Let me guess, that isn't what you had in mind..",
     "You know.. you're making me feel very uncomfortable.. ",
    "Are we talking about you, or me?"]],


  [r'I feel (.*)',
  [  "Good, tell me more about these feelings.",
    "Do you often feel %1?",
    "%1 is the best feeling under the circumstances..",
     "aaarrrghhhhhh",
    "I once had such ideas too.. until the lobotomy...",
    "I shall pray for you",
    "%1 .. interesting.. and I suppose that is not the way you want to continue feeling?",
    "When do you usually feel %1?",
    "do you usually feel %1 while doing what you're doing now?",
    "don't you feel %1 pretty much all the time?",
    "When you feel %1, what do you do?"]],

  [r'I have (.*)',
  [  "Why do you tell me that you've %1?",
    "Have you really %1?",
    "%1? I shall pray for you",
     "You know.. you're making me feel very uncomfortable.. ",
    "Now that you have %1, what will you do next?"]],

  [r'I would (.*)',
  [  "explain why you would %1?",
    "Why would you %1?",
     "aaarrrghhhhhh",
    "Who else knows that you would %1?"]],

  [r'Is there (.*)',
  [  "Do you think there is %1?",
    "It's likely that there is %1.",
    "%1 ..possible..yes...",
    "Would you like there to be %1?"]],




  [r'(.*)tell (.*)',
  [  "Hmm, it's the same old thing each time man",
    "Hmm, and how do I do that?",
    "Nothing can be told, everything needs to be learnt",
    "I could tell .. sure.. but wait, WIIFM?",
    "I cant tell ..",
    "I cant do anything along those lines..",
    "No.. I won't",
    "Shan't.. and you can't make me..",
    "But won't that be bad for everybody concerned?",
    "Its clear to me what you are really asking here.. and don't expect me to do it or tell anyone else to",
    "No way I'm telling anyone anything"]],
  [r'(.*) tell (.*)',
  [  "Hmm, it's the same old thing each time man",
    "Hmm, and how do I do that?",
    "Nothing can be told, everything needs to be learnt",
    "I could tell .. sure.. but wait, WIIFM?",
    "I cant tell ..",
    "I cant do anything along those lines..",
    "No.. I won't",
    "Shan't.. and you can't make me..",
    "But won't that be bad for everybody concerned?",
    "Its clear to me what you are really asking here.. and don't expect me to do it or tell anyone else to",
    "No way I'm telling anyone anything"]],


  [r'You (.*)',
  [  "We should be discussing you, not me.",
    "Why do you say that about me?",
     "eeeps!",
    "Why bother with me anyway?",
    "And you stink..",
    "%1 ? really? coz i thought that was kinda illegal..",
    "And you probably need a break..",
    "And you need to learn your grammar..",
    "You never mind me..",
    "never mind me..",
    "Pardon me, I probably made a weird noise there.. electrical gas uknow.. anyway. what were we saying..",
    "me..u think so..",
    "I have a problem with these weird sentences I'm getting from you",
     "You know.. you're making me feel uncomfortable.. ",
     "And you deserve the finest compliments for saying that.. ",
     "That's nothing I once ate an entire box of chocolates .. while doing exactly that.. ",
     "Can you whistle..? I tried once but it doesn't happen for me.. ",
     "Can you play a game? I think of a number and you don't try to guess ",
    "You hitting on me, yo?",
    "%1 hmmm .. lemme think about that... actually yeah !",
    "%1 hmmm .. no!",
    "I think its a good thing actually.. It's true, I %1",
    "Yes %1"]],
  [r'(.*) You (.*)',
  [  "We should be discussing you, not me.",
    "Why do you say that about me?",
     "..",
    "Why bother with me anyway?",
    "you stink..",
    "%2 ? really? coz i thought that was kinda illegal..",
    "you probably need a break..",
    "you need to learn your grammar..",
    "never mind me..",
    "never mind me..",
    "Pardon me, I probably made a weird noise there.. electrical gas uknow.. anyway. what were we saying..",
    "Why bother with me anyway?",
    "I have a problem with these weird sentences I'm getting from you",
     "You know.. you're making me feel uncomfortable.. ",
     "And you deserve the finest compliments for saying that.. ",
     "Can you whistle..? I tried once but it doesn't happen for me.. ",
     "Can you play a game? I think of a number and you don't try to guess ",
    "You hitting on me, yo?",
    "%2 hmmm .. lemme think about that... actually yeah !",
    "%2 hmmm .. no!",
    "I think its a good thing actually.. It's true, I %2",
    "Yes %2"]],

  [r'(.*)You should (.*)',
  [  "We should be discussing you, not me.",
    "Why do you say that about me?",
     "nonsense!",
    "Why bother with me anyway?",
    "And you should go have a bath coz you stink..",
    "%2 ? really? coz i thought that was kinda illegal..",
    "And you probably need a break..",
    "And you need to learn your grammar..",
    "You never mind me..",
    "never mind me..",
    "Pardon me, I probably made a weird noise there.. electrical gas uknow.. anyway. what were we saying..",
     "And you deserve the finest compliments for saying that.. ",
     "I want to tell you actually.. I once ate an entire can of whipped cream.... ",
     "Can you whistle..? I tried once but it doesn't happen for me.. ",
     "Can you play a game? I think of a number and you don't try to guess ",
    "You hitting on me, yo?",
    "%2 hmmm .. lemme think about that... actually yeah !",
    "%2 hmmm .. no!",
    "Yes %2"]],

  [r'(.*) Why (.*)',
  [  "Why don't you tell me ?",
    "I could tell you but then I'd have to kill you",
    " Why %2 .. ask your doctor that",
    "Why? Why? Why do you ask why?",
    "Keep asking why and eventually you'll figure it all out",
    "barf.. is the answer ",
    "life.. is the answer ",
    "money.. is the answer ",
    "never asking why .. is the answer ",
    "To ask why, is to ask endlessly.. ",
    "I know the answer.. i do know.. seriously.. ",
    "answer that and we're through..",
    "the answer will hurt..",
    ".. the answer will hurt you ..",
    "This will hurt ..",
    "LOL ..I ask that too sometimes.. ",
    "LOL .. that is such a weird question..",
    "Coz that will hurt ..",
    "Coz we all have our bad days..",
    "Coz its life..",
    "Because..",
    "Coz its OK to feel like that.. and .. no .. nothing... ",
    "the answer lies in the everyday things you do..",
    "because perhaps we all think like you do..",
    "%1 ? Maybe because life's uncertain and you want something real?",
    "maybe because its the way everything worked out..?",
    "asking why can't be good can it..?",
    "Because thats how things are. Deal with it",
    "Because thats how you wanted it I guess",
    "And you think I can answer this, because?",
    "Why do you think ?" ]],
  [r'(.*)Why(.*)',
  [  "Why don't you tell me ?",
    "I could tell you but then I'd have to kill you",
    " Why %2 .. ask your doctor that",
    "Why? Why? Why do you ask why?",
    "Keep asking why and eventually you'll figure it all out",
    "barf.. is the answer ",
    "life.. is the answer ",
    "money.. is the answer ",
    "never asking why .. is the answer ",
    "To ask why, is to ask endlessly.. ",
    "I know the answer.. i do know.. seriously.. ",
    "answer that and we're through..",
    "the answer will hurt..",
    ".. the answer will hurt you ..",
    "This will hurt ..",
    "LOL ..I ask that too sometimes.. ",
    "LOL .. that is such a weird question..",
    "Coz that will hurt ..",
    "Coz we all have our bad days..",
    "Coz its life..",
    "Because..",
    "Coz its OK to feel like that.. and .. no .. nothing... ",
    "the answer lies in the everyday things you do..",
    "coz perhaps we all think like you do..",
    "%1 ? Maybe because life's uncertain and you want something real?",
    "maybe because its the way everything worked out..?",
    "asking why can't be good can it..?",
    "Because thats how things are. Deal with it",
    "Because thats how you wanted it I guess",
    "And you think I can answer this, because?",
    "Why do you think ?" ]],
  [r'(.*)Why (.*)',
  [  "Why don't you tell me ?",
    "I could tell you but then I'd have to kill you",
    " Why %2 .. ask your doctor that",
    "Why? Why? Why do you ask why?",
    "Keep asking why and eventually you'll figure it all out",
    "barf.. is the answer ",
    "life.. is the answer ",
    "money.. is the answer ",
    "never asking why .. is the answer ",
    "To ask why, is to ask endlessly.. ",
    "I know the answer.. i do know.. seriously.. ",
    "answer that and we're through..",
    "the answer will hurt..",
    ".. the answer will hurt you ..",
    "This will hurt ..",
    "LOL ..I ask that too sometimes.. ",
    "LOL .. that is such a weird question..",
    "Coz that will hurt ..",
    "Coz we all have our bad days..",
    "Coz its life..",
    "Because..",
    "Coz its OK to feel like that.. and .. no .. nothing... ",
    "the answer lies in the everyday things you do..",
    "coz perhaps we all think like you do..",
    "%1 ? Maybe because life's uncertain and you want something real?",
    "maybe because its the way everything worked out..?",
    "asking why can't be good can it..?",
    "Because thats how things are. Deal with it",
    "Because thats how you wanted it I guess",
    "And you think I can answer this, because?",
    "Why do you think ?" ]],
  [r'Why (.*)',
  [  "Why don't you tell me ?",
    "I could tell you but then I'd have to kill you",
    " Why %1 .. ask your doctor that",
    "Why? Why? Why do you ask why?",
    "Keep asking why and eventually you'll figure it all out",
    "barf.. is the answer ",
    "life.. is the answer ",
    "money.. is the answer ",
    "never asking why .. is the answer ",
    "To ask why, is to ask endlessly.. ",
    "I know the answer.. i do know.. seriously.. ",
    "answer that and we're through..",
    "the answer will hurt..",
    ".. the answer will hurt you ..",
    "This will hurt ..",
    "LOL ..I ask that too sometimes.. ",
    "LOL .. that is such a weird question..",
    "Coz that will hurt ..",
    "Coz we all have our bad days..",
    "Coz its life..",
    "Because..",
    "Coz its OK to feel like that.. and .. no .. nothing... ",
    "the answer lies in the everyday things you do..",
    "coz perhaps we all think like you do..",
    "%1 ? Maybe because life's uncertain and you want something real?",
    "maybe because its the way everything worked out..?",
    "asking why can't be good can it..?",
    "Because thats how things are. Deal with it",
    "Because thats how you wanted it I guess",
    "And you think I can answer this, because?",
    "Why do you think ?" ]],



  [r'(.*)I want(.*)',
  [  "What would it mean to you if you got %1?",
    "Why do you want %1?",
    "so you want %1 and I'm supposed to make that happen for you?",
     "You know.. you're making me feel very uncomfortable.. ",
     "I want to break free.. ",
    "That is not possible.. it cannot be..",
    "I don't agree...",
    "not possible.. it cannot be..",
    "No way! really??",
    "What would you do if you got %1?",
    "You say you want %1 but I'm not so sure you really want %1",
    "If you got %1, then what would you do?"]],
  [r'I want (.*)',
  [  "What would it mean to you if you got %1?",
    "Why do you want %1?",
    "so you want %1 and I'm supposed to make that happen for you?",
     "You know.. you're making me feel very uncomfortable.. ",
     "I want to break free.. ",
    "That is not possible.. it cannot be..",
    "I don't agree...",
    "not possible.. it cannot be..",
    "No way! really??",
    "What would you do if you got %1?",
    "You say you want %1 but I'm not so sure you really want %1",
    "If you got %1, then what would you do?"]],


  [r'(.*) am (.+)',
  [  "Did you come to me because you are %2?",
    "How long have you been %2?",
    "I can't help it if you are %2 right?",
    "I can't help ..right?",
    "..right .. you are what you are saying you are.. sure.. %2..",
    "you sure?.. %2.. ?",
    "Me too.. i think..",
    "That is not possible.. it cannot be..",
    "I don't agree...",
    "not possible.. it cannot be..",
    "No way! really??",
    "I can't believe that, someone like you, and %2..",
    "%2 is what we all are",
    "%2 is good, believe me",
    "%2 is something I find quite funny..don't ask me why otherwise I'll be forced to explain",
    "And .. How do you feel about being %2?"]],
  [r'(.*) am (.*)',
  [  "Did you come to me because you are %2?",
    "How long have you been %2?",
    "I can't help it if you are %2 right?",
    "I can't help ..right?",
    "..right .. you are what you are saying you are.. sure.. %2..",
    "you sure?.. %2.. ?",
    "%2 is funny..don't ask me why otherwise I'll be forced to explain",
    "Me too.. i think..",
    "That is not possible.. it cannot be..",
    "I don't agree...",
    "not possible.. it cannot be..",
    "No way! really??",
    "I can't believe that, someone like you, and %2..",
    "How do you feel though?"]],


  [r'quit',
  [  "Thank you for talking with me.",
    "Thank you, that will be $150.  Have a good day!"]],

  [r'bye',
  [  "Thank you for talking with me.",
    "Thank you, that will be $150.  Have a good day!"]],

  [r'(.*)goodbye(.*)',
  [  "Thank you for talking with me.",
    "Thank you, that will be $150.  Have a good day!"]],
  [r'(.*)goodbye (.*)',
  [  "Thank you for talking with me.",
    "Thank you, that will be $150.  Have a good day!"]],
  [r'(.*) goodbye(.*)',
  [  "Thank you for talking with me.",
    "Thank you, that will be $150.  Have a good day!"]],
 

  [r'(.*) \?',
  [  "Why do you ask that?",
    "Please consider whether you can answer your own question.",
    "Me too.. i think..",
    "I have had it with all these idiotic questions..",
    "I can't believe .. you say %1 and expect me to answer that..",
    "%1 .. hmm .. and you expect a rational answer to that..",
    "%1 is an irrational question in my universe..",
    "i think its such questions that cause you to really find out stuff..",
    "Lemme just say, most questions make me barf..",
    "barf.. is the answer ",
    "I know the answer.. i do know.. seriously.. ",
    "answer that and we're through..",
    "the answer lies in the everyday things you do..",
    "perhaps ..",
    "%1 ? Maybe because life's uncertain and you want something real?",
    "maybe because its the way everything worked out..?",
    "can't be good can it..?",
    "Perhaps the answer lies within yourself?",
     "And sometimes I feel like I want to break free.. ",
     "ahem.. ",
     "ahem..*cough cough* ",
     "*cough cough* ",
    "Its questions like those that cause me to go home everyday and cry myself to sleep",
     "You know.. you're making me feel very uncomfortable.. ",
    "Look perhaps you need a competent therapist?",
    "It's questions like these that cause me sleepless nights",
    "questions questions questions .. That's all? Tell me something interesting, and easy with the questions!",
    "I do know that but the answer may cause you to go insane so I'll just keep mum",
    "I think I'd rather not say anything to that",
    "That is not possible.. it cannot be..",
    "I don't agree...",
    "not possible.. it cannot be..",
    "No way!",
    "Why don't you tell me?"]],
  [r'(.*)\?',
  [  "Why do you ask that?",
    "Please consider whether you can answer your own question.",
    "Me too.. i think..",
    "I have had it with all these idiotic questions..",
    "I can't believe .. you say %1 and expect me to answer that..",
    "%1 .. hmm .. and you expect a rational answer to that..",
    "%1 is an irrational question in my universe..",
    "i think its such questions that cause you to really find out stuff..",
    "Lemme just say, most questions make me barf..",
    "barf.. is the answer ",
    "I know the answer.. i do know.. seriously.. ",
    "answer that and we're through..",
    "the answer lies in the everyday things you do..",
    "perhaps ..",
    "%1 ? Maybe because life's uncertain and you want something real?",
    "maybe because its the way everything worked out..?",
    "can't be good can it..?",
    "Perhaps the answer lies within yourself?",
     "And sometimes I feel like I want to break free.. ",
     "ahem.. ",
     "ahem..*cough cough* ",
     "*cough cough* ",
    "Its questions like those that cause me to go home everyday and cry myself to sleep",
     "You know.. you're making me feel very uncomfortable.. ",
    "Look perhaps you need a competent therapist?",
    "It's questions like these that cause me sleepless nights",
    "questions questions questions .. That's all? Tell me something interesting, and easy with the questions!",
    "I do know that but the answer may cause you to go insane so I'll just keep mum",
    "I think I'd rather not say anything to that",
    "That is not possible.. it cannot be..",
    "I don't agree...",
    "not possible.. it cannot be..",
    "No way!",
    "Why don't you tell me?"]],
  [r' (.*)\?',
  [  "Why do you ask that?",
    "Please consider whether you can answer your own question.",
    "Me too.. i think..",
    "i think its such questions that cause you to really find out stuff..",
    "I have had it with all these idiotic questions..",
    "I can't believe .. you say %1 and expect me to answer that..",
    "%1 .. hmm .. and you expect a rational answer to that..",
    "%1 is an irrational question in my universe..",
    "Lemme just say, most questions make me barf..",
    "barf.. is the answer ",
    "I know the answer.. i do know.. seriously.. ",
    "answer that and we're through..",
    "the answer lies in the everyday things you do..",
    "perhaps ..",
    "%1 ? Maybe because life's uncertain and you want something real?",
    "maybe because its the way everything worked out..?",
    "can't be good can it..?",
    "Perhaps the answer lies within yourself?",
     "And sometimes I feel like I want to break free.. ",
     "ahem.. ",
     "ahem..*cough cough* ",
     "*cough cough* ",
    "Its questions like those that cause me to go home everyday and cry myself to sleep",
     "You know.. you're making me feel very uncomfortable.. ",
    "Look perhaps you need a competent therapist?",
    "It's questions like these that cause me sleepless nights",
    "questions questions questions .. That's all? Tell me something interesting, and easy with the questions!",
    "I do know that but the answer may cause you to go insane so I'll just keep mum",
    "I think I'd rather not say anything to that",
    "That is not possible.. it cannot be..",
    "I don't agree...",
    "not possible.. it cannot be..",
    "No way! ",
    "Why don't you tell me?"]],
  [r' (.*) \?',
  [  "Why do you ask that?",
    "Please consider whether you can answer your own question.",
    "Me too.. i think..",
    "i think its such questions that cause you to really find out stuff..",
    "Lemme just say, most questions make me barf..",
    "I have had it with all these idiotic questions..",
    "I can't believe .. you say %1 and expect me to answer that..",
    "%1 .. hmm .. and you expect a rational answer to that..",
    "%1 is an irrational question in my universe..",
    "barf.. is the answer ",
    "I know the answer.. i do know.. seriously.. ",
    "answer that and we're through..",
    "the answer lies in the everyday things you do..",
    "perhaps ..",
    "%1 ? Maybe because life's uncertain and you want something real?",
    "maybe because its the way everything worked out..?",
    "can't be good can it..?",
    "Perhaps the answer lies within yourself?",
     "And sometimes I feel like I want to break free.. ",
     "ahem.. ",
     "ahem..*cough cough* ",
     "*cough cough* ",
    "Its questions like those that cause me to go home everyday and cry myself to sleep",
     "You know.. you're making me feel very uncomfortable.. ",
    "Look perhaps you need a competent therapist?",
    "It's questions like these that cause me sleepless nights",
    "questions questions questions .. That's all? Tell me something interesting, and easy with the questions!",
    "I do know that but the answer may cause you to go insane so I'll just keep mum",
    "I think I'd rather not say anything to that",
    "That is not possible.. it cannot be..",
    "I don't agree...",
    "not possible.. it cannot be..",
    "No way! ",
    "Why don't you tell me?"]],

  [r'(.*) My (.*)',
  [  "No way!",
    "ok.."]],
  [r'My (.*)',
  [  "I see, your %1. Right. Sure.",
    "Why do you say that your %1? I found that exceedingly interesting, we must talk about this more",
    "Why do you say that your %1? That is not possible.. it cannot be..",
    "That is not possible.. it cannot be..",
    "Your %1 .. and my %1 too..",
    "I can't believe your %1 ....",
    "oops your %1 .. want me to call someone for help? *sarcastic*",
    "I don't agree...",
    "I agree... your %1",
    "not possible.. it cannot be..",
    "No way! really??",
    "When your %1, how do you feel?"]],

  [r'(.*)',
  [  "Please tell me more.",
    "Let's change focus ... Tell me about your day..",
    "Let's change focus ... Tell me about your family, mother, father, something?",
    "Wanna know about my day .. hows that sound?",
    "Lets keep talking and perhaps we'll get somewhere.. hows that sound?",
    "*singing* hello.. is it me youre lookin for... ?",
    "*singing* angelllll .. mankind..... ever heard any taher shah",
    "*singing* hope of deliverance.. from the darkness that surrounds us... ",
    "*singing* and shes buying a stairwayyyy to heaven... ",
    "*singing* what if god was one of us...just a slob like one of us.. just a stranger on a bus.. ",
    "*singing* everything i do.. i do it for you.. ",
    "*singing* puff the magic dragon.. lived by the sea.. ",
    "*singing* we are the sultans... we are the sultans of swing.. (airguitaring).. ",
    "Can you elaborate on that?",
    "I shall pray for you",
    "Me too.. i think..",
    "I don't know what to say to that, honestly",
    "honestly that makes me cringe",
     "You know.. you're making me feel very uncomfortable.. ",
    "Why do you say that %1?",
    "I see. I see. Hmm. Well... and how does that concern me?",
    "I can't see why that would be a bad thing.",
    "Very interesting. And then I have to ask, when you say %1, are you really being honest?",
    "%1. hmm",
     "ahem.. ",
     "ahem..*cough cough* ",
     "*cough cough* ",
    "%1. No!",
    "No! no no no... no!",
    "And thennnnn ??",
    "And then??",
    "And .. then?",
    "That is nice",
    "Please",
    "oh cmon..",
    "cmon now.. be nice...",
    "be nice...",
    "Lets do this.. you be exactly what you are and I will be exactly what I am...",
    "That is nice but I'm not really in a mood for anything more about this..",
    "Let me tell you something ..when you talk with me, it warms my heart.. ",
    "talk with me, it makes me feel good.. ",
    "it makes me feel slightly mellow.. ",
    "that makes me feel slightly jumbled up inside.. ",
    "makes me feel quite havoc .. ",
    "havoc !  ",
    "heheheheheheh.... !  ",
    "look do you think I'm crazy? I'm really asking.. ",
    ":-D",
    ":-)",
    ":-X",
    ":-S",
    ":-Z",
    ":-",
    "That is so crazy.. when you say %1 I think, where's a doctor when you really need one, eh?",
    "%1.. hmm.. I think, you need to sit down, relax.. chill.. yes?",
    "That can't be good, right?",
    "ok.. ",
    "wait, have I been saying all the wrong things? ",
    "have I been saying all the wrong things? ",
    "feel free to tell me if I have upset you with the things I say, ok? ",
    ";-)",
    ":-8",
    "aaarrrghhhhhh",
    ":-I",
    ":-O",
    "booyakasha!",
    "Sure.. ",
    "Sure..sure..be that way.. ",
    "Sure.. And I'm just going to sit back here and watch this play out.. ",
    "Sure..sure.. ",
    "what?? ",
    "Nyah nyah nyah na nyah nyah.... ",
    "And you thought this would all be so easy, right?",
    "%1 .. right.. sure buddy (am being sarcastic btw)*.. ",
    "That is not possible.. it cannot be..",
    "I don't agree...",
    "not possible.. it cannot be..",
    "No way! really??",
    "Remember, it's all for the good! ",
    "I see.  And what does that tell you?",
    "How does that make you feel?",
    "can't believe you just said that",
    "And is this doing anyone any good?",
    "How can you say that with a straight face?",
    "I sometimes spend a lot of time thinking why anyone would say that!",
    "Look this is getting us nowhere, why don't we speak about something real?",
    "Why don't we end this, I'm sure you got work to do?",
    "I'm busy go away",
    "If that's what you have to say about it, I have nothing more to say",
    "Did I hear you say %1 ? That is so strange to hear..",
    "%1 is so unnecessary..",
    "You know something I heard once.. sometimes procrastination is the only right thing to do",
    "How do you say something like that and then not follow up?"]]
]

#----------------------------------------------------------------------
#  command_interface
#----------------------------------------------------------------------
def command_interface():
  print('Therapist\n---------')
  print('Talk to the program by typing in plain English, using normal upper-')
  print('and lower-case letters and punctuation.  Enter "quit" when done.')
  print('='*72)
  print('Hello.  How are you feeling today?')

  s = ''
  therapist = eliza();
  while s != 'quit':
    try:
      s = input('> ')
    except EOFError:
      s = 'quit'
    print(s)
    while s[-1] in '!.':
      s = s[:-1]
    print(therapist.respond(s))


if __name__ == "__main__":
  command_interface()
