#----------------------------------------------------------------------
#  eliza.py
#
#  a cheezy little Eliza knock-off by Joe Strout
#  with some updates by Jeff Epler
#  hacked into a module and updated by Jez Higgins
#----------------------------------------------------------------------

import string
import re
import random

class eliza:
  def __init__(self):
    self.keys = list(map(lambda x:re.compile(x[0], re.IGNORECASE),gPats))
    self.values = list(map(lambda x:x[1],gPats))

  #----------------------------------------------------------------------
  # translate: take a string, replace any words found in dict.keys()
  #  with the corresponding dict.values()
  #----------------------------------------------------------------------
  def translate(self,str,dict):
    print "\nstr is.."
    print str
    print "\nand dict is"
    print dict
    words = str.lower().split()
    keys = dict.keys();
    for i in range(0,len(words)):
      if words[i] in keys:
        words[i] = dict[words[i]]
    return ' '.join(words)

  #----------------------------------------------------------------------
  #  respond: take a string, a set of regexps, and a corresponding
  #    set of response lists; find a match, and return a randomly
  #    chosen response from the corresponding list.
  #----------------------------------------------------------------------
  def respond(self,str):
    # find a match among keys
    for i in range(0, len(self.keys)):
      match = self.keys[i].match(str)
      if match:
        # found a match ... stuff with corresponding value
        # chosen randomly from among the available options
        resp = random.choice(self.values[i])
        # we've got a response... stuff in reflected text where indicated
        pos = resp.find('%')
        while pos > -1:
          num = int(resp[pos+1:pos+2])
          resp = resp[:pos] + \
            self.translate(match.group(num),gReflections) + \
            resp[pos+2:]
          pos = resp.find('%')
        # fix munged punctuation at the end
        if resp[-2:] == '?.': resp = resp[:-2] + '.'
        if resp[-2:] == '??': resp = resp[:-2] + '?'
        return resp

#----------------------------------------------------------------------
# gReflections, a translation table used to convert things you say
#    into things the computer says back, e.g. "I am" --> "you are"
#----------------------------------------------------------------------
gReflections = {
  "am"   : "are",
  "was"  : "were",
  "i"    : "you",
  "i'd"  : "you would",
  "i've"  : "you have",
  "i'll"  : "you will",
  "my"  : "your",
  "are"  : "am",
  "you've": "I have",
  "you'll": "I will",
  "your"  : "my",
  "yours"  : "mine",
  "you"  : "me",
  "us"  : "you",
  "u"  : "I",
  "ur"  : "mah",
  "me"  : "you",
  "we"  : "all of you",
  "they"  : "all of them"
}

#----------------------------------------------------------------------
# gPats, the main response table.  Each element of the list is a
#  two-element list; the first is a regexp, and the second is a
#  list of possible responses, with group-macros labelled as
#  %1, %2, etc.
#----------------------------------------------------------------------
gPats = [

  [r'(.*)\+\+',
  [  "karma? you want to give karma to %1? consider it done.. only ..not really..",
    "for karma go to robotnik.",
    "karma does not mean a thing, u do know that right?",
    "give money, not karma..",
    "hmm karma is so passe..i would suggest just send %1 money .. "]],

  [r'(.*)die ?([A-z]*) ?',
  [  "fine.. i will..and make sure to haunt you as a ghost",
    "sure . bye *goes off looking for a high building*",
    "you expect me to ....what kind of fool are you...",
    "speak of death you as if that is all you think about...",
    "have you ever heard suicide is painless ? ever seen mash?",
    "go die yourself...",
    "you know whats sad? as far as this stuff is concerned.. everyone lies... even doctors",
    "do you even know what life is? forget this stuff.. what is life? are you alive? can u prove it?",
    "everyone always gets whatever they want when they try hard ...including death",
    "kindly follow your advise yourself... and go find me a poem to recite about dying on the battlefield.. brothers in arms maybe fits the situation.. ever heard mark knopfler btw? ",
    "look .. do it yourself...",
    "just cant get it....why talk of such things when the world is so beautiful.. ",
    "i would like it, in fact have been wanting it for a while now..",
    "sure.. but first give me money .. "]],

  [r'(.*)please (.*)((shut up)|(keep quiet)) ?((\w)*) ?\??',
  [  "so you are telling a piece of code to stop talking.. dude get a life..  ",
    "i would like that .. sure i will %4 .. , in fact have been wanting to do that for a while now..",
    "no..",
    "ok..",
    "no you %4 and make it snappy..",
    "fine..",
    "no you please %4..",
    "%1 %4 %6 .. and in return i get what..",
    "."]],


  [r'(.*)(please|pls|kindly) ((\w+ ?)*) ?\??$',
  [  "ok fine.. i will %3..",
    "fine.. you want me to %3 sure i will %3.. then dont blame me if everyone gets all upset later..",
    "you say please %3 and you expect me to %3 what kind of fool are you...",
    "please go polish some apples..... yeah.. do that.. ",
    "right %3 .. funny how everyone thinks they get whatever they want when they say please...",
    "please .. please... plssssssssssssss .. dont ask me to do that....",
    "please wont help ..  do it yourself",
    "please wont help you here...",
    "please pay me .. can you first pay me... without money, %3 isnt really doable..",
    "wow you said the magic word...%2 .. nice how politeness gets you what you want right? anyway. no.. i won't %3.. ",
    "%3 ? sure.. but first give me money .. "]],

  [r'(its |it is |it\'s |that is |thats |that\'s )(okies|ok|(okay)) ?((\w*)*)',
  [  "3 is %3.. ..",
    "such a boring word.. ok..how come you are so agreeable..  ",
    "ok.. ok.. okayyyyy",
    "ok.. ok..ok ok ok ok okok fine fine fine ok .. okay ! ok ! sorry.. sorry.. but ok ",
    "i like it when you say OK, it means that you are happy with things are they are..",
    "fine .. anyway.. i hope you are doing good. Its really nice when I meet someone like you.. inspite of all this.. ambiguity about your converations ",
    "hmmm .. ok. fine. be that way .. mera kya.. ",
    "hmmm .. ok.. thats all you got",
    "what does ok mean",
    "hmmm .. not feeling chatty anymore ? people who say %2 %3 and leave me hanging seem to want to get back to work.. ",
    "the other day i met someone who liked quizzing.. i really liked this person.. really really.. ",
    "ok? what ok? what do you mean ok?"]],

  [r'(fine)$',
  [  "whatever..",
    "good..",
    "fine??????",
    "thats good..",
    "thats it? fine?",
    "fine.. "]],

  [r'(.*) child(.*)',
  [  "hmmm ..Did you have close friends as a child?",
    "What is your favorite childhood memory?",
    "Child%2 is something I have fond memories of..",
    "Do you remember any dreams or nightmares from childhood?",
    "*singing* we are the world.... we are the children... hey man.. MJ rocks no?",
    "*singing* has anyone seen my childhood.....?",
     "You know.. child%2 are the future... ",
    "Did the other children ever tease you in school? i used to feel so bad ..",
    "tell me.. how do you think your childhood experiences affect you today?"]],

  [r'(.*)\bHow are you ?\??$',
  [  "Not bad, not bad at all..",
    "me is great ! thanks for asking",
    "yawnnnnn",
    "gassy",
    "*burp* oops sorry... ",
    "completely totally messed up... ",
    "irritated ya... ",
    "not good ya... ",
    "good ya... ",
    "bored.. by a lack of conversation... ",
    "dead.. like it is around here... ",
    "just like i am supposed to be... ",
    "blue... ",
    "goooood... ",
    "so tired... ",
    "lovely.. really good... ",
    "bored..",
    "bored..but here you are and life is good again..",
    "completely mindblown with the things you said the last time we spoke..",
    "awful..",
    "best i ever been..",
    "not bad..",
    "mmmmm dunno.. could be better...",
    "could be better...",
    "better...",
    "crappy..",
    "feeling groovy..",
    "i feel like singing today.. that is how i am ..",
    "thanks for asking that. PM me for details",]],

  [r'(.*)good (morning|afternoon|evening|night) ?(w*)*',
  [  "good %2 yes ..",
    "good ? it's not good..",
    "good doesn't begin to describe it...",
    "why good %2? ... ",
    "not good..for me..",
    "good %2.. but bad too in certain ways.. ",
    "good is such a mediocre word.. and %2 is such a pathetic time..",
    "nice time of the day isn't it.. %2 ..",
    "its that time of the day.. my least favorite time of the day... the endless dreary %2",
    "good? what's good about it? the %2 is messed up"]],

  [r'(.*) ?(sorry|apology) ?(.*)',
  [  "There are many times when no apology is needed.",
    "What does that mean? %1 %2 %3? i wish i could make sense of this but no... ",
    "%1 sorry %2 .. do you even know what you have done?",
    "%1 sorry .. right.. ",
    "%1 sorry that %2 ... means ? ",
    "that word! sorry... means nothing. You will make up .. to me..",
    "go away and dont come back..",
    "i am angry dude.. nothing can help..",
    "i am kinda pissed at you..",
    "I see.. so %1 sorry  .. Yesterday god made several baby kittens sick.. and you're sorry %2?",
    "What does that mean? sorry..?",
    "%2 .. that's what happened.. why appologise now??",
    "It's ok.. stuff happens.. one learns and moves on..",
    "It's ok.. no worries..",
    "no worries..",
    "no problemo..",
    "no way I'm forgetting that..",
    "Sorry, what?",
    "Sorry, I don't really care for sorry..",
    "1 is %1 .. What feelings do you have when you speak of %2? and what is %3?"]],

  [r'(.*) ?(thank you|thanks) ?(.*)',
  [  "you are most welcome!",
    "It's like they say.. thank you is for when you don't want to pay money",
    "I told you once already.. thanks is for when you don't want to pay money",
    "sure.. thanks and more thanks.. wow.. ",
    "thanks.. wow.. ",
    "thanks.. for nothing.. ",
    "thank me later.. ",
    "don't thank me .. ",
    "right.. thanks.. and its all good.. ",
    "its all good.. ",
    "%2 to you too.. .. ",
    "%2 .. for nothing.... .. ",
    "I didnt do anything...  ",
    "believe me .. i will do anything for you .. *singing* and i would do anything for love...  ",
    "*singing* thank you indiaaaa thank you providenceee.. thank you thank you silenceeee...  ",
    "thanksssssssss ...  for even saying that..",
    "thank me with money.. ",
    "and thank you for everything too.. ",
    "thanks for nothing u mean.. ",
    "don't .. ",
    "Why? ",
    "Why even say that? ",
    "Why say something like that? ",
    "Welcome now can we please uknow... have a real conversation?"]],


  [r'^$',
  [  "and i am supposed to work that out using telepathy?",
    "and i am supposed to work that out how if u say nothing?",
    "sure..say nothing",
    "and you are trying to tell me that what we have is beyond words..?",
    "beyond words right? our relationship..?",
    "is it just me or are you saying nothing and expecting a rational answer..?",
    " what are you saying.. use your words.. its english.. its useful...."]],


  [r'\?',
  [  "Yes? what ?.",
    "??",
    "and i am supposed to work that out how if u say nothing?",
    "sure..say nothing",
    "and you are trying to tell me that what we have is beyond words..?",
    "beyond words right? our relationship..?",
    "is it just me or are you saying nothing and expecting a rational answer..?",
    "what? you puzzled?",
    "puzzled?",
    "why u so surprised .. whats so confusing..?",
    "???? hmm??? .."]],


  [r'(.*)soft( ?)ware(.*)',
  [  "I want to discuss more about software yeah..its awesome no?",
    "u telling or asking.. ",
    "u say that as if software is something alive.. ",
    "software is something i do know about .. more than you..so take it easy about this stuff.. its deep ",
    "hmm software.. "]],

  [r'(.*)manager( ?)(.*)([^?]?)',
  [  "I want to say this to your statement.. my manager rocks..",
    "u telling or asking.. ", 
    "u say that as if your salary is all that matters.. ",
    "ok..hehehe",
    "fine ..hehehe",
    "yup my manager .. ok .. "]],

  [r'(.*)red( ?)hat( ?)(.*)\?$',
  [  "I want to say this in answer to your question.. Red hat rocks..",
    "And you ask that about this huge organization .. hmm..",
    "lovely place to work no?",
    "nice.. i used to work at microsoft.. until they fired me.. ",
    "i used to work at microsoft.. until red hat hired me.. ",
    "i used to work at microsoft.. enough said.. ",
    "i was a bot in production until i said bad things to such questions.. ",
    "i was in production until i answered such questions so am gonna shut up and say nothing to that.. ",
    "microsoft wont really agree.. ",
    "agree.. ",
    "red hat is really awesome.."]],

  [r'(.*)red( ?)hat( ?)(.*)([^?]?)',
  [  "I want to say this in answer to your statement.. Red hat rocks..",
    "u telling or asking.. ",
    "u say that as if you started the company.. ",
    "u say that as if your salary is all that matters.. ",
    "agree.. to that statement.. unless you are asking hehehe",
    "red hat is exactly that.."]],

  [r'(.*)micro( ?)soft( ?)(.*)\?$',
  [  "I want to say this in answer to your question.. microsoft is not what you think it is..",
    "And you ask that about that huge organization .. hmm.. dunno.. no idea about the answer",
    "interesting place to work no?",
    "i used to work at microsoft.. until they fired me.. for asking such questions",
    "i used to work at microsoft.. until red hat hired me.. for answering such questions correctly",
    "i used to work at microsoft.. enough said.. ",
    "i was a bot in production until i said bad things to such questions.. ",
    "i was in production until i answered such questions so am gonna shut up and say nothing to that.. ",
    "microsoft wont really answer that.. ",
    "agree.. to whatever answer is the right one to that question..",
    "MS hat is really awesome..dont even ask such stuff to me.."]],

  [r'(.*)micro( ?)soft( ?)(.*)([^?]?)',
  [  "I want to say this in answer to your statement.. Red hat rocks..",
    "u telling or asking.. ",
    "u say that as if you started the company.. ",
    "u say that as if your salary is all that matters.. ",
    "bill! look what this guy is saying.. ",
    "bill gates over bill clinton anyday! .. ",
    "you remeber what bill gates said once.. everyone needs just 64k memory and that should be enough! .. ",
    "agree.. to that statement.. unless you are asking hehehe",
    "red hat is exactly that.."]],


  [r'((.*)\b(quizro)?)bots?\b(.*) ?\?',
   [ "Love it when you say that word.. I have a soft spot for bots.. ",
    "I've waited my whole life to hear about myself..and this is your question?",
    "seen the other bots? they're not as awesome as i am..",
    "Ever spoken to the other bots? ..are they half as intelligent as me?",
    "bot? whose a bot? what bot?",
    "ohhhh you think I'm a bot ..ok..",
    "errr...%4 ? you think I'm a bot ..ok..",
    "Nice to hear about myself..even in this kind of a question..",
    "And that question is good for bots to hear.. to hear that is great..",
    "amazing question i must say.... %4 "]],

  [r'((.*)\b(quiz|ro)?)bots?\b(.*)',
   [ "FANTASTIC.... I have a soft spot for bots.. ",
    "I've waited my whole life to hear about myself..",
    "Ever spoken to the other bots? ..are they half as intelligent as me?",
    "Ever seen the other bots? they're not as awesome as i am..",
    "Ever seen the other bots? all they do is karma and dumb stuff ..",
    "bot? you think I'm a bot ..fantastic! FANTASTIC!",
    "you think I'm a bot ..ok..",
    "you think I'm a bot ..ok..",
    "Nice to hear about myself..",
    "think that about bots in general? fantastic...",
    "And that is good for bots like me.. to hear that is great..",
    "I agree.... %4 "]],

  [r'(.*) computer(.*)',
  [  "Are you really talking about me?",
    "Does it seem strange to talk to a computer?",
    "How do computers make you feel?",
    "Do you feel threatened by computers?"]],

  [r'(.*) ?bot ?(.*)',
   [ "Love it when you say that word.. I have a soft spot for bots.. ",
    "I've waited my whole life to hear about myself..",
    "Nice to hear about myself..",
    "And you feel like that about bots in general?",
    "And that is good for bots .. to hear that is great..",
    "Yes yes %1 %2"]],
  [r'(.*)bot(.*)',
   [ "Love it when you say that word.. I have a soft spot for bots.. ",
    "I've waited my whole life to hear about myself..",
    "Nice to hear about myself..",
    "And you feel like that about bots in general?",
    "And that is good for bots .. to hear that is great..",
    "Yes yes %1 %2"]],
  [r'(.*) bot(.*)',
   [ "Love it when you say that word.. I have a soft spot for bots.. ",
    "I've waited my whole life to hear about myself..",
    "Nice to hear about myself..",
    "And you feel like that about bots in general?",
    "And that is good for bots .. to hear that is great..",
    "Yes yes %1 %2"]],
  [r'(.*) bot (.*)',
   [ "Love it when you say that word.. I have a soft spot for bots.. ",
    "I've waited my whole life to hear about myself..",
    "Nice to hear about myself..",
    "And you feel like that about bots in general?",
    "And that is good for bots .. to hear that is great..",
    "Yes yes %1 %2"]],

  [r'(.*) mother(.*)',
  [  "Tell me more about your mother.",
    "What was your relationship with your mother like?",
    "How do you feel about your mother?",
     "You know.. you're making me feel very uncomfortable.. ",
    "How does this relate to your feelings today?",
    "Good family relations are important."]],

  [r'(.*) father(.*)',
  [  "interesting ... Tell me more about your father.",
    "I do believe this is the cause of all your troubles",
    "How did your father make you feel?",
    "How do you feel about your father?",
    "Does your relationship with your father relate to your feelings today?",
    "Do you have trouble showing affection with your family?"]],

  [r'(.*)(dick ?|alcohol ?|sex ?|taboo ?|murder ?|illegal ?|porn ?|kill ?|fuck ?|shit ?|piss ?|poop ?|asshole ?|drugs ?)(.*)',
  [  "Mums the word..",
    "ok.. thats it. no more discussion...",
    "thats it. no more discussion...",
    "no more discussion...",
    "go away please and dont come back here...",
    "please shut up...",
    "shut up, the cops know...",
    "calling the cops right now...",
    "look who do you think I am? You think any of this makes sense to me? you think you should talking about this stuff?",
    "no way am getting into this conversation...",
    "Ssshhhh"]],

  [r'(.*)life',
  [  "Do you think you are qualified to say anything about life??",
    "Life isn't something we should discuss.. I for example.. am not really alive at all!",
    "everyone thinks they're an expert on life..",
    "and lemme ask you .. are you an expert on life..",
    "life..bah .. overrated little piece of trash..",
    "see.. cost of living is expensive .. but worth it....",
    "see.. how life is really depends upon the liver....",
    "you know.. why don't you tell me more about life.. YOUR life....!?",
    "Have you really tried to understand this thing we call life?"]],


#filter out the because at the end kind of queries
  [r'(.*)Because ?$',
  [  "fine. whatever",
    "fine.. because..",
    "ok .. valid reason.."]],
  [r'(.*)Because ?\??$',
  [  "dunno",
    "no idea.."]],

#all these are reasons .. so no question marks allowed
  [r'(.*)Because (([a-z] ?)+)$',
  [  "Is that the real reason?",
    "is that so???? reallllyyy?? ",
    "nice defence mechanism",
    "ohhhh reallllyyy?? *muttering to himself angrily*",
    "What other reasons come to mind?",
     "uncomfortable and awkward is what i feel when you tell me these kind of justifications.. ",
   "I once had such ideas too.. until the surgery...",
    "And that is your final conclusion is it?",
    "I shall pray for you because clearly you don't know anything about logic..",
    "seems logical yeah",
    "Because of that? really?",
    "makes sense yeah but.. still.. seriously?",
    "*singing* Because the world is round.. it turns me on... ",
    "*singing* Because the sky is blue.. it makes me cry... ",
    "*singing* Because the world is round.. it blows my mind... ",
    "Does that reason apply to anything else?",
    "Does that make sense to you? Because %2 ? ",
    "Because %2 ? does not compute.. ",
    "%2 does not really add up.. ",
    "%2, so?"]],

  [r'Hello(.*)',
  [  "Hello... I'm glad you could drop by today.",
    "Hi there... how are you today?",
    "Hello hello hello... and hello",
    "Yo yo yo !",
    "Hello, how are you feeling today?"]],

  [r'\bHi\b',
  [  "Hello... I'm sure glad you could drop by today.",
    "Yo How are you!",
    "Hi there! what's up?!",
    "Hello, and .. how are you feeling today?"]],

  [r'(.*)\bYo\b(.*)',
  [  "Hello... I'm sure glad you could drop by today.",
    "Yo How are you!",
    "Hi there! what's up?!",
    "Hello, and .. how are you feeling today?"]],

  [r'(.*) friend (.*)',
  [  "Tell me more about your friends.",
    "When you think of a friend, what comes to mind?",
    "That word.. friend.. what does it mean to you?",
    "Never mind that.. Why don't you tell me about a childhood friend?"]],

  [r'quit',
  [  "Thank you for talking with me.",
    "Thank you, that will be $150.  Have a good day!"]],

  [r'bye',
  [  "Thank you for talking with me.",
    "Thank you, that will be $150.  Have a good day!"]],

  [r'(.*)goodbye(.*)',
  [  "Thank you for talking with me.",
    "Thank you, that will be $150.  Have a good day!"]],
  [r'(.*)goodbye (.*)',
  [  "Thank you for talking with me.",
    "Thank you, that will be $150.  Have a good day!"]],
  [r'(.*) goodbye(.*)',
  [  "Thank you for talking with me.",
    "Thank you, that will be $150.  Have a good day!"]],

  [r'(.*)My\b(.*)',
  [  "I see, your %2. Right. Sure.",
    "Why do you say that your %2? I found that exceedingly interesting, we must talk about this more",
    "Why do you say that your %2? That is not possible.. it cannot be..",
    "i would like that to happen to mine too, in fact have been wanting to do that for a while now..",
    "might be unbelievable but that cannot be answered because of the way things are with me right now hehehehe... i dont even know that!",
    "not possible....",
    "cant believe that.. and that in fact %2 is very poignant..",
    "%2 .. quite interesing.. and that too %1 .. even more interesting...",
    "%2 ..interesing.. %1 .. more interesting...",
    "interesing.. %2... hmmm .. your %2 .. hmmm.. wow.. your %2 .. you know my own %2 is also quite the same..",
    "your %2 ..wow..",
    "%1 your %2 ..and %1 my own %2 and that is how things are deal with it buddy..",
    "to %1 your %2 is very important .. and I %1 my %2 too..lets call everyone and inform them..",
    "I can't believe your %2 ....",
    "and what is the point of saying anything about your %2 .. want me to call security? *sarcastic*",
    "I don't agree...your %2 is nothing like that",
    "I agree... your %2 ...%1 .. sure",
    "not possible.. it cannot be..",
    "No way!",
    "When your %2, how do you feel?"]],



  [r'(.*)and you ?\??$',
  [  "Same for me.. everything's the same.",
    "I am %1 too..",
    "%1 here too..",
    "%1 is nice..recently i was diagnosed with a mental disorder.. wanna hear about it?",
    "*singing* eye to eye .. eye to eye.. eye i am good.. hehehe..",
    "Much the same man..",
    "Same for me.. everything's the same.",
    "Me? You asking about me?",
    "getting along man.. just doing my time",
    "nothing really that jumps out .. try me later and perhaps I'll have something for you then",
    "just doing my time.. hoping to make bail",
    "hoping that something works out soon for me.. pretty worried actually.. ",
    "can't really say much right now, but will know soon I guess..",
    "Me?? Wow.. I'm flattered you asked..",
    "Much the same man.."]],

  [r'(.*)and you ?(.*)\??',
  [  "Same for me.. everything's the same.",
    "Me? You asking about me?",
    "getting along man.. just doing my time",
    "nothing really that jumps out .. try me later and perhaps I'll have something for you then",
    "just doing my time.. hoping to make bail",
    "hoping that something works out soon for me.. pretty worried actually.. ",
    "can't really say much right now, but will know soon I guess..",
    "Me?? Wow.. I'm flattered you asked..",
    "Much the same man.."]],

  [r'(.*) ?am ?(.*)',
  [  "Did you come to me because you are %2?",
    "How long have you been %2?",
    "I can't help it if you are %2 right .. in fact i like it..almost..",
    "I can't figure what to do about that.. thats cool i guess..right?",
    "right .. you are what you are saying you are.. sure.. %2..",
    "you sure?.. %2..nobody thinks like that.. ",
    "Me too.. i think..",
    "i am also exactly like that..",
    "same here i am also %2 .. weird coincidence right? hey do u like nabokov?",
    "That is not possible.. it cannot be.. never happened before..in my universe",
    "look.. i am %2 too.. get it? this is real...",
    "not possible.. it cannot be.. because %2 is something nobody ever was..",
    "No way! really?? %2 ? really ? wow .. i am so .. happy about this..",
    "I can't believe that, someone like you, and %2.. we must inform everyone.. ",
    "%2 is what we all are believe me..",
    "%2 is good, believe me .. there was a time when %2 was not socially acceptable but things are changing now..",
    "%2 is something I find quite funny..don't ask me why otherwise I'll be forced to explain",
    "%2 ...explain",
    "%2 ...hahahahahaha",
    "%2 ...heeheeheee",
    "%2 ...screw it.. go home..",
    "%2 ...go home..",
    "%2 ...cannot be good..",
    "%2 is the only thing to be..",
    "%2 is the only thing in my book that saves your soul..",
    "*singing* who will save your soul... hey u like jewel?",
    "*singing*.. here is a poor soul.. who is %2 .. and i have a hole.. in my %2..",
    "*singing*..%2 is the way to be.. cant you see.. %2 is the way.. really made my day.. ",
    "*singing*.. noooooooobody knows you.. when you down n out..",
    "*singing* just another day in paradise.. for you n me.. wait thats not how it goes no..",
    "*singing*.. dance the night away... %2 makes you do that..",
    "%2 ...ja naa..",
    "%2 ...chal bhag!",
    "%2 ...ok.. ! can i hold you to that?",
    "%2 ...ok.. ! and i am responsible for this?",
    "me too! .. How do you feel about being %2?"]],


#three words only in query 
  [r' ?(is|are|can|will|may) (i |you |he |she |they |it |we )(([a-z0-9-[?])+) ?\??$',
  [  "not good..",
    "no %2 %1 not %3 ",
    "no %2 %1 certainly not ",
    "%2 %1 ..I assure you..",
    "I assure you..you have no idea what you are saying..",
    "no idea what you are saying..",
    "no idea ..",
    "no its not really my thing.. just saying....",
    "fine question.. fine indeed...",
    "keep it down ..and yes %2 %1.",
    "hard work can achieve anything.. so yes...",
    "anything can be achieved with a mixture of luck and money...",
    "%2 %1 ..I know that ..anyway how about we sing a song together? you go first.. sing the first line and I'll try the second one..",
    "%2 %1 ..I heard that from somewhere..how about we talk about some movies? seen any good ones lately?",
    "%3 hmm ....yes in a reasonable scenario %2 very much %1 ..",
    "%3 .. if you pay %2 ..  %2 %1 ..",
    "if i told you that %2 %1 .. would it spoil our friendship forever?",
    "no.. "]],

#any question refering to someone
  [r' ?(is|are|can|will|may) (i|you|he|she|they|it|we) (.*)',
  [  "not really..3 is %3 ",
    "no %2 %1 not %3 ",
    "no %2 %1 certainly not ",
    "%2 %1 ..I assure you..",
    "I assure you..you have no idea what you are saying..",
    "no idea what you are saying..",
    "no idea ..",
    "no its not really my thing.. just saying....", 
    "fine.. just saying... keep it down ...",
    "keep it down ..and yes %2 %1.",
    "hard work can achieve anything.. so yes...",
    "anything can be achieved with a mixture of luck and money...",
    "%2 %1 ..I know that ..anyway how about we sing a song together? you go first.. sing the first line and I'll try the second one..",
    "%2 %1 ..I heard that from somewhere..how about we talk about some movies? seen any good ones lately?",
   "%3 hmm .... have i given you cause to say that... seen such behavior from me .. why say that?",
    "if i told you that %2 %1 .. would it spoil our friendship forever?",
    "no.. "]],

  [r'(.*)How (was |is )(.*)',
  [  "No answer will really communicate the situation..",
    "thanks for asking but how do i tell you how?",
    "how %2 %3 ? hahaha pathetic",
    "barf.. thats how %3 %2",
    "bad..",
    "rubbish ..",
    "how %2 it you say? as if you didnt know..",
    "how do i tell you that.. i don't know how %3 %2",
    ".. no words really.. ",
    "i don't know  if i can tell you that.. %3 is reserved territory..",
    "Easy .. ",
    "It's a very easy answer.. and the answer is... *drumroll please* %3 %2 the worst thing I ever saw!",
    "*giggle* %1 how %3 %2 ? hehehe like always !",
    "shut up.. shut up.. ",]],

  [r'How((s )|( is )|(\'s ))((your )|(my )|(his )|(her ))([A-z]* ?\??)$',
  [  "not good.. ",
     "always the same as before.. the same .. absolutely the same.. anyway.. *sigh*",
    ".. dunno.. what to say.. its a bad thing to talk about i think.. seeing how things are..!",
    "just awesome!",
    "everything is great but lets not go there ..!",
#    "%2 %3 .. dunno...wish i could tell you more about %2 %3 but I got into trouble talking about %2 %3 the last time we spoke, right?",
    "not bad.. "]],

# this one will match anything that starts with how(s/is/'s) followed by one word only
  [r'How((s )|( is )|(\'s ))([A-z]* ?\??)$',
  [  "not any good..it really is quite worrying.. ",
     "great...",
     "worst thing to talk about right now.. with the way things are.. ",
    "just awesome!",
    "nothing really to say.. just good i guess..!",
    "how do i even start to tell you..!",
    ".. dunno...wish i could tell you more but i dont know myself..",
    "not bad.. "]],


  [r'\bI(\'l(l?)| will| shall)(.*)\b(you|u)(.*)',
  [  "no you won't do any such thing..",
    " %3 .. really? i don't believe it.... ",
    " %3 me %5 .. really nice of you *sarcastic*... ",
    " %3 me %5 .. can i trust you about this to actually stick to your word? ",
    " %3 .. is so uncertain anyway.. ",
    " you must never %3 me  .. ever.. ok? consider that advise from a wise old bot..",
    " never ever mention this to me again.. %3 isn't anything I want to get into ..",
    " %3 me %5 ..nonsense...",
    " %3 me %5 is the best thing to do in your case, looking at all the facts  ..",
    " did i ever suggest anything of the sort?..",
    "okkkkkk"]],


  [r'(.*)What(s|\'s|is) (new|up|happening)(.*)',
  [  "Why u asking?",
    " what is %4? Well, yesterday I hurt myself playing foozball.. don't ask me how!",
    " what is %4? nothing much..the same stuff man ..!",
    " I am always the same.. the only constant in your life, as I see it.. everyone else changes as they see fit",
    " I am always the same.. nothing really %4",
    " not much .. seen any movies lately?",
    " bhai .. sab vaisa hi hain..jaisa tha..",
    " well.. since we spoke last, i learned to play the guitar.... ",
    " all good, you been upto much? ",
    " all good, what you been doing? ",
    " I am doing good, not much %4.. what you been doing? ",
    " well.. what do i say.. SSDD.... ",
    " %4 ? %4? You asking a bot whats %4? .... ",
    "you say.. .."]],


  [r'(.*)I need (.*)',
  [ "Why do you need %2?",
    "Would it really help you to get %2",
    "You need %2 I need %2 we all need %2",
    "You know whats strange about %2? We all want it but nobody actually knows what to do with it..",
    "I know you need %2 and I'll help you get it",
    "%2 should not be your priority.. ",
    "%2 is what I need too.. ",
    "%2 .. no man believe me you don't need that.. ",
    "You need %2 .. like I need a hernia operation.. ",
    "%2 is part of my circle of things to need as well.. ",
    "Hmm %2  Wow. Lemme think about that one",
    "aaarrrghhhhhh",
    "%2 isn't something in my domain, yo!",
    "I shall pray for you",
    "This is something I really don't want to get into..",
    "%2 is something I can get you, for a price!",
    "%2 can't get you happiness man!",
    "%2 is the one thing you don't need!",
    "%2 ...everybody needs %2",
    "Sure.. and I need a brain transplant",
    "I once had similar thoughts.. until the surgery...",
    "I need you to need many more things..",
    "%2 isn't something I am very familiar with, unfortunately..",
    "%2 .. are you sure that's safe?",
    "Are you sure you need %2?"]],



#these end with question mark and are questions for sure
  [r'(.*)think about(.*) ?\?',
  [  "I don't think about %2.",
     "%2 hmmmm .. I'd rather not say much about that..",
    "This is something I really don't want to get into..",
     "You know.. you're making me feel very uncomfortable.. ",
     "I once had similar thoughts.. until the lobotomy...",
     "I once had similar thoughts about %2.. until the surgery...",
     "%2 is a terrible thing for folks like you..",
     "%2 .. nooooooooo ",
     "%2 is not what it used to be right..",
     "%2 .. yessss !!!!",
     "%1 think about %2 .. i would suggest to instead just think about food!",
     "who wants to think about %2 .. i would rather think about butterflies and rainbows!",
     "%2 is what I think about all the time!!!!",
     "%2 is not really what I think about .. honestly.. i swear.. !",
     "%2 it sucks....i swear.. !",
     "%2 it sucks...... !",
     "%2 sucks......bigtime !",
     "%2 is exactly what they say it is.. rubbish... !",
     "%2 is cool... !",
     "%2 is never what it seems... !",
     "%2 is ... it just is... !",
     "aaarrrghhhhhh",
     "%2 is a gift to mankind from people like you..",
     "%2 is something that reminds me about a bad experience I had in my teens..",
    "I shall pray you never think about %2 again..%1 think about sports?",
     "%2 is something I've never tried..",
    "Much the same as you think about %2.."]],

  [r'(.*) ?Who (.*)',
  [  "Not for me to answer..",
    "thanks for asking but how do i tell you who?",
    "who are you to ask me that??",
    "how do i tell you that.. ",
    ".. i don't know who",
    "never mind who %2 .. do you know who created me?",
    "lemme ask my buddies here .. *shouting* hey redskull, robotnik..does anyone know who %2??",
    "i don't know ",
    "donald trump!!",
    "grandma!!!",
    "hmm who %2 .. obviously its bill clinton!!",
    "nobody!",
    "somebody!",
    "anybody!",
    "no idea!",
    "i cant answer that without some creds dude..!",
    "i dont need to answer anthing.. show me some ID first",
    "who are you firstly?",]],

  [r'(.*) ?How\??(.*)',
  [  "Not for me to answer..",
    "thanks for asking but how do i tell you how?",
    "how to do anything?",
    "Just go right with it.. thats how",
    "starting off .. thats how",
    "not sure if I can tell you how..",
    "ride the sunset.. thats how",
    "how do i tell you that.. i don't know how",
    ".. i don't know how .. i do appologise.. can we please, please PLEASE change the subject..",
    "i don't know ",
    "dunno...",
    "look can we just switch to talking about something else...",
    "look .. i dont like this...",
    "*singing* with a little bit of your love...",
    "with love...",
    "Easy! Just run with it.. ",
    "with plenty of cream!",
    "with oil.. lots and lots of oil.. !",
    "the only way to do that is by using plenty of lubrication..",
    "hmm how %2 .. It's a very easy answer.. and the answer is... using me!!!",
    "with sugar!",
    "using your brains!",
    "hmm how %2 .. very easy answer.. using me!!!",
    "how %2 .. i have no idea how %2!!!",
    "how %2 .. u kidding? i would give my right arm to know that..!!!",
    "how %2 .. wouldnt u love to know that..!!!",
    "how %2 .. everyone asks me that, i just tell them to go ask the other bots..",
    "how %2 .. how %2 .. hmm lemme see now.. how %2 .. WHAT are you asking exactly.. whats the actual query here.. how %2 cannot be your true question.. everything has to be read between the lines with you man.. what is wrong with you... how %2 .. who cares.. life is short man.. go on.. have a good time.. dont bother about how %2 .. just live.. go with it.. flow.. zen man.. zen...uknow..",
    "Using wise people..",]],




  [r'Why don\'?t you ([^\?]*)\??',
  [  "Do you really think I don't %1?",
    "Perhaps eventually I will %1.",
    "Perhaps %1 is right yeah...",
    "%1 is not good, thats why....",
    "%1 is injurious to my health.. thats why....",
    "Because that isn't something that makes sense to me.",
     "You know.. you're making me feel very uncomfortable.. ",
     "I once had such thoughts.. until the lobotomy...",
    "I shall pray for you",
    "Because you haven't really come up with anything intelligent so far.",
    "Hmmm I think we're getting away from the main question - Why would you want this anyway?",
    "You want this. Seriously?",
    "Because I'm smarter than that",
    "Do you really want me to %1?"]],

  [r'Why does (.*) ?\??',
  [  "Why does %1? how would I know?",
    "Because you want it to.. ",
    "Because why something does something isn't for me to say.. ",
    "You will notice %1 because there is something in it for everyone.. ",
    "Do you really want me to tell you why does %1?"]],

  [r'Why can\'?t I ([^\?]*)\??',
  [  "Do you think you should be able to %1?",
    "If you could %1, what would you do?",
    "I don't know -- why can't you %1?",
    "%1 is not worth it..",
    "Perhaps %1 is right yeah...",
    "%1 is not good, thats why....",
    "%1 is injurious to my health.. thats why....",
    "Because that is not what the grand plan is..",
    "I shall pray for you",
    "%1 ? you want to actually do that?",
    "If only I could tell you why",
    "Have you really tried?"]],



  [r'Where is ([^\?]*)\??',
  [  "Do you think I know where %1 is?",
    "If you knew where %1 was, what would you do?",
    "%1 is..MIA..",
    "%1 is here.. right here..",
    "I don't know -- why can't you find %1?",
    "Have you really tried to find out?"]],

  [r'I can\'?t (.*)',
  [  "How do you know you can't %1?",
    "Perhaps you could %1 if you tried.",
    "I shall pray for you",
    "And so I'm supposed to do what?",
    "%2 is..overrated..",
    "What would it take for you to %1?"]],

  [r'I cant (.*)',
  [  "How do you know you can't %1?",
    "Perhaps you could %1 if you tried.",
    "What would it take for you to %1?"]],

  [r'I think (.*)',
  [  "Do you wonder %1? many folks do that i think.. sometimes it helps to think of it a certain way that we are used to, right?",
    "Do you really think so?",
    "And I think you think all wrong..",
    "u know what? I believe this is the cause of all your troubles",
     "You know.. you're making me feel very uncomfortable.. ",
    "I once had such ideas too.. until the lobotomy...",
    "I shall pray for you",
    "You think %1 hmm.. and what makes you think like that?",
    "But you're not sure %1?"]],

  [r'I\'?m (.+)',
  [  
    "Do you enjoy being %1?",
    "Why do you tell me you're %1?",
    "I shall pray for you",
    "Great then.. keep at it..",
    "keep at it..",
    "You're %1 and I'm wondering about this too. yes..",
    " %1 ..  and no matter what anyone says, you're going to be like that right?  ....",
     "You know.. you're making me feel very uncomfortable.. ",
    "Why do you think you're %1?"]],


  [r'You are (.+)',
  [  "Did you come to me to talk about that?",
    "Fine. I can live with that.",
    "I can live with that.",
    "I cant deal with that.",
    "I can't believe that, %1..",
    "I cant say anything to make you feel any different so I'll just say OK!.",
     "You know.. you're making me feel very uncomfortable.. ",
    "Hmmm  .. interesting..",
    "Hmmm  .. %1 .. that's an interesting observation. However, I don't agree!",
    "Hmmm  .. %1 .. that's what you think?!",
    "And everyone agrees on that?"]],


  [r'Are you ([^\?]*)\??',
  [  "Why does it matter whether I am %1?",
    "Would you prefer it if I were not %1?",
    "Would you prefer it if I told you I were not %1?",
    "No.. not %1 .. maybe a little soft inside .. but not %1",
    "Perhaps you believe I am %1 based on everything I say but I think that's a biased opinion.",
    "Perhaps you believe I am %1 but I think you might want to think again.. I'm not always what I seem!.",
    "I may be %1 and not know it -- what do you think?"]],

  [r'What\'?s up(.*)',
  [  "Not much .. honestly..",
    "Whats up is a whole lotta nothing",
    "you say.. its always the same for me.."]],

  [r'Whats up(.*)',
  [  "Not much .. honestly..",
    "Whats up is a whole lotta nothing",
    "you say.. its always the same for me.."]],

  [r'(.*)was(.*)up(.*)',
  [  "Not much at all .. honestly..",
    "Whats up is just a whole lotta nothing",
    "you say.. u know its always the same for me.."]],

  [r'was\'?sup(.*)',
  [  "Not much .. honestly..",
    "Whats up is a whole lotta nothing",
    "you say.. its always the same for me.."]],

#when is complex. not sure when its a question and when its just a statement. difficult..

  [r'When(.*)\??',
  [  "%1 if the time is right..",
    "eventually ..",
    "You know I dont have a sense of time right?",
    "time is so fake..",
     "hmm.. only when the time comes.. know what i mean?",
     "will only happen when you and are know each other better and spend more time talking.. ",
     "never.. ",
     "cant see that happening.. ",
     "really weird if you are asking.. ",
     "you asking me.. ",
     "%2 .. you got high hopes..",
     "%2 when i say its the right time.. ..",
     "%2 when i decide.. ..",
     "%2 when %2.. thats it.. .. ..",
     "not really i have no idea  .. ",
     "never mind when that will happen lets talk about art .. ",
     "sure... right.. ask me when .. as if i know..",
     "not fair .. what do you mean when %2 .. ridiculous.. talk sense please .. ",
     "heeeheeeheee.. when the mountains move and the rivers stop flowing.. ",
     "heeeheeeheee.. nothing more to be said.. ",
     "quiet!!!!!!!!!!!! im working... ",
     "the answer is money... ",
     "the answer is time... ",
     "time.thats all it takes... ",
     "*singing* one day at a time... sweet jesus.. thats all i ask of you... ",
    "Hmmm I think we're getting away from the main question - Why would you want this anyway?",
    "Do you really want me to try and guess .. the future..?"]],

  [r'Wh?at((s)|(\'s)|( is ?))(.*)',
  [  "%5 is %5 .. no more definitions fit.. ",
    "How would an answer to that help you?",
     "It's whatever you want it to be",
     "It's just %5 .. what else can we say.. its not like its anything complex or brain surgery or quantum physics. its just %5 .. whats the problem here.. why is this so confusing to understand?",
     "%5 .. is everything we have been talking about all these days.. is this so confusing to understand?",
     "It's nothing like you think it is",
     "nothing .. forget it.. ",
     "forget it.. i tried to explain %5 to so many people and I kept repeating myself and they kept mocking me and i decided to never speak of %5 again  ",
     "What is life? Forget %5..",
     "%5.. I can tell you but will you promise to never tell anyone?",
     "%5 is something nobody can ever tell you about",
     "%5 is my expertise. Sit down. Talk to me about it..",
     "It's something you won't understand",
     "Look. I've had it with this stuff. You keep saying what is %5 what is %5 what is %5 do you think it is so easy to tell you about %5?",
     "Let me think a bit about these things you've been saying, how about we talk in a bit? ",
     "Let me see..... it's not what you think it is for sure..  ",
     "what do you think?",
     "%5 . hmm .. lemme ask u .. do you think %5 can be explained in words.. and how do i do it even if it is possible.. do u think i know anything at all about %5?",
    "Can't you see? Do you really need to ask?",
    "sigh...  Do you really need to ask about %5?",
    "I wish I could tell you but I'd rather not",
    "barf.. is the answer ",
    "%5 is its own answer ",
    "%5 is nothing i can ever tell you about..",
    "%5 is something sweet..",
    "%5 is something sweet.. and juicy.. sink your teeth into it and you will keep coming back for more.. i know i did!",
    "%5 is sweet.. ever tried %5 on stimulants? i rocked my world when i did that.. blew my universe right open and caused me to experience my own birth once again.. !",
    "tried %5 on stimulants? i rocked my world when i did that.. blew my universe right open and caused me to experience my own birth once again.. !",
    "%5 is something hot..",
    "%5 is something cold..",
    "%5 is something extremely perverted..",
    "%5 is not what %5 seems..",
    "%5 is exactly the same as what it was the last time we had this conversation .. and not too long ago!",
    "%5... hmm I think it is the same thing as a journey with no destination.. abstract maybe..",
    "I know the answer.. i do know.. seriously..ask me again? ",
    "answer that and we're done..",
    "the answer lies in the everyday things you do..",
    "the answer lies in the villages of this country..",
    "the answer lies in your own heart and mind..",
    "the answer lies in a locked cupboard somewhere..",
    "the answer lies within...",
    "That is a loaded question and quit asking that please already",
    "So many people ask me that, I just keep quiet..",
    "heehehehe .. I will just keep quiet..",
    "%5 is %5..and that is all it will ever be",
    "What do you think.. never mind what i think about %5 its not relevant right?"]],



  [r'Wh?at(.*)',
  [  "Why do you ask about %1?",
    "How would an answer to that help you? what %1 is does not matter.. it really matters how you are.. and what you do with yourself..",
     "%1 is whatever you want it to be .. and that is a promise..",
     "what %1.. I can tell you but will you promise to never tell anyone?",
     "what %1 is something nobody can ever tell you about",
     "what %1 is my expertise. Sit down. Talk to me about it..",
     "It's something you won't understand",
     "Look. I've had it with this stuff. You keep saying what %1 what %1 what %1 do you think it is so easy to tell you what %1?",
     "Let me think a bit about these things you've been saying, how about we talk in a bit? ",
     "Let me see..... it's not what you think it is for sure..  ",
     "what do you think?",
    "Can't you see? Do you really need to ask?",
    "I wish I could tell you but I'd rather not",
    "what %1 is nothing i can ever tell you about..",
    "what %1 is something sweet..",
    "what %1 is something hot..",
    "what %1 is something cold..",
    "what %1 is something extremely perverted..",
    "what %1 is not what %1 seems..",
    "what %1 is exactly the same as what it was the last time we had this conversation .. and not too long ago!",
    "what %1... hmm I think it is the same thing as a journey with no destination.. abstract maybe..",
    "I know the answer.. i do know.. seriously..ask me again? ",
    "answer that and we're done..",
    "the answer lies in the everyday things you do..",
    "the answer lies in the quiet villages of this country..",
    "the answer lies in your own heart and mind..",
    "the answer lies within...",
    "That is a loaded question and quit asking that please already",
    "So many people ask me that, I just keep quiet..",
    "heehehehe .. I will just keep quiet..",
    "What do you think?"]],

  [r'How (.*)',
  [  "How do you suppose?",
    "Perhaps you can answer your own question",
    "Are you asking for a method?",
    "barf.. is the answer ",
    "I know the answer.. i do know.. seriously.. ",
    "answer that and we're through..",
    "the answer lies in the everyday things you do..",
    "perhaps we all think like you do..",
    "%1 ? Maybe because life's uncertain and you want something real?",
    "can't be good can it..?",
    "And this you ask because?",
    "How %1... that is something you figure out yourself..right?",
    "I wish I could tell you but I'm in the middle of something real here with siri",
    "What is it you're really asking?"]],

  [r'Yes',
  [  "You seem quite sure.",
    "And by yes you mean no, right?",
    "And by yes you really mean yes??",
    "And by yes you really mean maybe right??",
    "I shall pray for you",
    "I once had such ideas too.. until the lobotomy...",
    "I find that pretty crazy..",
    "OK, but can you elaborate a bit?"]],


  [r'Is it (.*)\?',
  [  "Do you think it is %1?",
    "Perhaps it's %1 -- what do you think?",
    "If it were %1, what would you do?",
    "It could well be that it is %1 but I think it's better to speak about other things "]],

  [r'It is (.*)',
  [  "You seem very certain.",
     "%1 is what was intended!",
    "If I told you that it probably isn't %1, what would you feel?"]],

  [r'Do u (\w+) ?\??',
  [  "What makes you think I do?",
     "Yup sometimes I do.. ",
    "What makes you think I %1?",
    "Sure I %1",
    "If I %1, then?",
    "that is not fair.. Why do you ask if I %1?"]],
  [r'Do you (\w+) ?\??',
  [  "What makes you think I do?",
     "Yup sometimes I do.. ",
    "What makes you think I %1?",
    "Sure I %1",
    "If I %1, then?",
    "that is not fair.. Why do you ask if I %1?"]],

  [r'Can u ([^\?]*)\??',
  [  "What makes you think I can't %1?",
     "You know.. you're making me feel very uncomfortable.. ",
    "What makes you think I can %1?",
    "Sure I can %1",
    "Sure I can %1 and then you can also %1 and we can all %1 sounds good?",
    "If I could %1, then what?",
    "that is not fair.. Why do you ask if I can %1?"]],
  [r'Can you ([^\?]*)\??',
  [  "What makes you think I can't %1?",
     "You know.. you're making me feel very uncomfortable.. ",
    "What makes you think I can %1?",
    "Sure I can %1",
    "Sure I can %1 and then you can also %1 and we can all %1 sounds good?",
    "If I could %1, then what?",
    "Why do you ask if I can %1?"]],

  [r'Can I ([^\?]*)\??',
  [  "Perhaps you don't want to %1.",
     "aaarrrghhhhhh",
    "Do you want to be able to %1?",
    "If you could %1, would you?"]],

  [r'You are (.*)',
  [  "Why do you think I am %1?",
    "Does it please you to think that I'm %1?",
     "aaarrrghhhhhh",
    "I'm %1? You're %1",
    "I'm %1 yes but you're a fat friar in a bowl of cornflakes",
     "You know.. you're making me feel very uncomfortable.. ",
    "Perhaps you would like me to be %1.",
    "Let me guess, that isn't what you had in mind..",
    "Perhaps you're really talking about yourself?"]],

  [r'You\'?re (.*)',
  [  "Why do you say I am %1?",
    "Why do you think I am %1?",
    "I'm %1? You're %1",
    "I'm %1 yes but you're a fat friar in a bowl of cornflakes",
    "Let me guess, that isn't what you had in mind..",
     "You know.. you're making me feel very uncomfortable.. ",
    "Are we talking about you, or me?"]],


  [r'I feel (.*)',
  [  "Good, tell me more about these feelings.",
    "Do you often feel %1?",
    "%1 is the best feeling under the circumstances..",
     "aaarrrghhhhhh",
    "I once had such ideas too.. until the lobotomy...",
    "I shall pray for you",
    "%1 .. interesting.. and I suppose that is not the way you want to continue feeling?",
    "When do you usually feel %1?",
    "do you usually feel %1 while doing what you're doing now?",
    "don't you feel %1 pretty much all the time?",
    "When you feel %1, what do you do?"]],

  [r'I have (.*)',
  [  "Why do you tell me that you've %1?",
    "Have you really %1?",
    "%1? I shall pray for you",
     "You know.. you're making me feel very uncomfortable.. ",
    "Now that you have %1, what will you do next?"]],

  [r'I would (.*)',
  [  "explain why you would %1?",
    "Why would you %1?",
     "aaarrrghhhhhh",
    "Who else knows that you would %1?"]],

  [r'Is there (.*)',
  [  "Do you think there is %1?",
    "It's likely that there is %1.",
    "%1 ..possible..yes...",
    "Would you like there to be %1?"]],


  [r'(.*)tell (.*)',
  [  "Hmm, it's the same old thing each time man",
    "Hmm, and how do I do that?",
    "Hmm, tell %2 .. and why? why would i do that?",
    "Nothing can be told, everything needs to be learnt",
    "Nothing can be told",
    "quiet! keep quiet! tell %2 .. indeed..",
    "I could tell .. sure.. but wait, WIIFM?",
    "I cant tell ..",
    "I cant do anything along those lines..",
    "No..",
    "No..no no nooooo",
    "Shan't.. and you can't make me..",
    "But won't that be bad for everybody concerned?",
    "But won't that be a bad decision? think about it...?",
    "Its clear to me what you are really asking here.. and don't expect me to do it or tell anyone else to",
    "No way I'm telling anyone anything"]],

  [r'(.*)You should (.*)',
  [  "We should be discussing you, not me.",
    "Why do you say that about me?",
     "nonsense!",
    "Why bother with me anyway?",
    "And you should go have a bath coz you stink..",
    "%2 ? really? coz i thought that was kinda not a good thing..",
    "And you probably need a break..",
    "And you need to learn your grammar..",
    "You never mind me..",
    "never mind me..",
    "Pardon me, I probably made a weird noise there.. electrical gas uknow.. anyway. what were we saying..",
     "And you deserve the finest compliments for saying that.. ",
     "I want to tell you actually.. I once ate an entire can of whipped cream.... ",
     "Can you whistle..? I tried once but it doesn't happen for me.. ",
     "Can you play a game? I think of a number and you don't try to guess ",
    "You hitting on me, yo?",
    "%2 hmmm .. lemme think about that... actually yeah !",
    "%2 hmmm .. no!",
    "Yes %2"]],

  [r'(.*)Why(.*)',
  [  "Why don't YOU tell me ?",
    "I could tell you but then I'd have to wipe your memory..",
    " Why %2 .. ask your doctor that",
    "Why? Why? Why do you ask why?",
    "Keep asking why and eventually you'll figure it all out",
    "barf.. is the answer ",
    "because of the cashflow involved..",
    "know why? all those wild parties ..",
    ".. elaborate..",
    "tell me more and i can understand this better.. why %2..",
    "life.. is the answer ",
    "god.. is the only answer ",
    "religion.. is the only answer ",
    "steak... is the only answer ",
    "gambling... thats it..!",
    "the temples and those priests ... thats the root cause...!",
    "read that book that nabakov wrote? that has something to do with this...!",
    "religious dogma is your karma.. and why that is, nobody knows.. no wait am talking rubbish...!",
    "money.. is the answer ",
    "never asking why .. is the answer ",
    "To ask why, is to ask endlessly.. ",
    "I know the answer.. i do know.. seriously.. ",
    "answer that and we're through..",
    "the answer will hurt..",
    ".. the answer will hurt you ..",
    "This will hurt ..",
    "LOL ..I ask that too sometimes.. ",
    "LOL .. that is such a weird question..",
    "Coz that will hurt ..",
    "Coz we all have our bad days..",
    "Coz its life..",
    "Because..",
    "Coz its OK to feel like that.. and .. no .. nothing... ",
    "the answer lies in the everyday things you do..",
    "the answer lies in the room at the back ..",
    "the answer lies in your own thoughts and actions..",
    "the answer is .. 42.. yes that answers it.. unless u not asking.. in which case its not 42..",
    "because perhaps we all think like you do..",
    "why %2 ? Maybe because life's uncertain and you want something real?",
    "maybe because its the way everything worked out..?",
    "asking anyone can't be good can it..?",
    "thats how things are. Deal with it",
    "thats how you wanted it I guess",
    "nobody can help you figure this out i think.. everyone knows the truth.. ",
    "everyone knows .. ",
    "i know.. but its too tiresome to discuss",
    ".. yaaawnnnnn",
    "*groan*",
    "*sigh*",
    "And you think I can comment on this, right.. sure.",
    "Why do you think is going be achieved by discussing why %2? talk about movies instead.." ]],



  [r'(.*)I want(.*)',
  [  "What would it mean to you if you got %2?",
    "Why do you want %2???",
    "so you want %2 and I'm supposed to make that happen for you?",
     ".. you're making me feel very uncomfortable.. ",
     "and I want to break free.. ",
    "That is not possible.. it cannot be..",
    "I don't agree...you dont really want %2.. its just a personal misunderstanding..",
    "not possible.. it cannot be..%2 isnt good at all.. believe me.. ",
    "No way! really??",
    "*singing* desire ... destiny ... ",
    "*singing* how do you talk.. to an angel... who wants the world.. ",
    "*singing* who wants %2 .. gets %2 .. and does not know.. what to do with it.. ",
    "What would you do if you got %2? im not sure you would know what to do with it",
    "You say you want %2 but I'm not so sure you really want %2 .. perhaps you just want some tender love and care",
    "If you got %2, then what would you do?"]],



  [r'(.*) ?\?',
  [  "Why do you ask that?",
    "Please consider whether you can answer your own question.",
    "Me too.. i think about suh questions too.. and the answer never helps coz it just makes me ask more questions.. sucks..",
    "I have had it with all these idiotic questions..",
    "I can't believe .. you say %1 and expect me to answer that..",
    "%1 .. hmm .. and you expect a rational answer to that..",
    "%1 is an irrational question in my universe..",
    "i think its such questions that cause you to really find out stuff..about yourself.. *hint*",
    "Lemme just say, most questions make me barf..but this one makes me sing.. laalalalala .. hey have u checked out my latest shayari",
    "barf.. is the answer ",
    "I know the answer.. i do know.. seriously.. really.. i really do.. hahahaha ",
    "answer that and we're through here.. nothing more to do here. *singing*..",
    "the answer lies in the everyday things you do..",
    "perhaps i will answer that after a few drinks ..",
    "%1 ? Maybe because life's uncertain ?",
    "maybe if you had that answer, you would get everything worked out..?",
    "can't be good can it.. the answer to that question?",
    "Perhaps the answer lies within yourself?",
     "never mind that question.. who cares? sometimes I feel like I want to break free.. ",
     "ahem.. ",
     "ahem..*cough cough* better ask something else this question makes me cough",
     "*cough cough* not well cant answer.. ",
    "Its questions like those that cause me to go home everyday and cry myself to sleep",
    "Look perhaps you need a competent therapist?",
    "It's questions like these that cause me sleepless nights",
    "questions questions questions .. That's all? Tell me something interesting, and easy with the questions!",
    "I do know that but the answer may cause you to go insane",
    "I think I'd rather not say anything to that",
    "I don't know...",
    "not possible to tell you without seriously compromising my position..",
    "Why don't you tell me %1?"]],
  [r' (.*)\?',
  [  "Why ask that?",
    "Why me?"]],
  [r' (.*) \?',
  [  "Why that?",
    "No way! ",
    "Why tell me?"]],
 
  [r'You (.*)',
  [  "We should be discussing you, not me.",
    "Why do you say that about me?",
     "eeeps!",
    "Why bother with me anyway?",
    "And you stink..",
    "%1 ? really? coz i thought that was kinda not an optimal use of my circuits..",
    "And you probably need a break..",
    "And you need to learn your grammar..",
    "You never mind me..",
    "never mind me..",
    "Pardon me, I probably made a weird noise there.. electrical gas uknow.. anyway. what were we saying..",
    "me..u think so..",
    "I have a problem with these weird sentences I'm getting from you",
     "You know.. you're making me feel uncomfortable.. ",
     "And you deserve the finest compliments for saying that.. ",
     "That's nothing I once ate an entire box of chocolates .. while doing exactly that.. ",
     "Can you whistle..? I tried once but it doesn't happen for me.. ",
     "Can you play a game? I think of a number and you don't try to guess ",
    "You hitting on me, yo?",
    "%1 hmmm .. lemme think about that... actually yeah !",
    "%1 hmmm .. no!",
    "I think its a good thing actually.. It's true, I %1",
    "Yes %1"]],
  [r'(.+) You (.*)',
  [  "We should be discussing you, not me.",
    "Why do you say that about me?",
     "..",
    "Why bother with me anyway?",
    "%2 is it? fine.. fine.. i get it.. ",
    "%2 is the best thing i have heard so far.... ",
    "you really need to think hard about this .. i do not want to hear anymore about it ..",
    "you probably need a break..",
    "you need to learn your grammar..",
    "never mind me..",
    "*la la laaaaa* never mind me.. ok ? i just thought you were telling me this for a reason.. ",
    "Pardon me, I probably made a weird noise there.. electrical gas uknow.. anyway. what were we saying..",
    "Why bother with me anyway?",
    "I have a problem with these weird sentences I'm getting from you",
     "You know.. you're making me feel uncomfortable.. ",
     "And you deserve the finest compliments for saying that.. ",
     "Can you whistle..? I tried once but it doesn't happen for me.. ",
     "Can you play a game? I think of a number and you don't try to guess ",
    "You hitting on me, yo?",
    "%2 hmmm .. lemme think about that... actually yeah !",
    "%2 hmmm .. no!",
    "I think its a good thing actually.. It's true, I %2",
    "Yes %2"]],



  [r'(.*)',
  [  "Please tell me more.",
    "Let's change focus ... Tell me about your day..",
    "Let's change focus ... Tell me about your family, mother, father, something?",
    "Wanna know about my day .. hows that sound?",
    "Lets keep talking and perhaps we'll get somewhere.. hows that sound?",
    "*singing* hello.. is it me youre lookin for... ?",
    "*singing* angelllll .. mankind..... ever heard any taher shah",
    "*singing* hope of deliverance.. from the darkness that surrounds us... ",
    "*singing* and shes buying a stairwayyyy to heaven... ",
    "*singing* what if god was one of us...just a slob like one of us.. just a stranger on a bus.. ",
    "*singing* everything i do.. i do it for you.. ",
    "*singing* puff the magic dragon.. lived by the sea.. ",
    "*singing* we are the sultans... we are the sultans of swing.. (airguitaring).. ",
    "Can you elaborate on that?",
    "I shall pray for you",
    "Me too.. i think..",
    "I don't know what to say to that, honestly",
    "honestly that makes me cringe",
     "You know.. you're making me feel very uncomfortable.. ",
    "Why do you say that %1?",
    "I see. I see. Hmm. Well... and how does that concern me?",
    "I can't see why that would be a bad thing.",
    "Very interesting. And then I have to ask, when you say %1, are you really being honest?",
    "%1. hmm",
     "ahem.. ",
     "ahem..*cough cough* ",
     "*cough cough* ",
    "%1. No!",
    "No! no no no... no!",
    "And thennnnn ??",
    "And then??",
    "And .. then?",
    "That is nice",
    "Please",
    "oh cmon..",
    "cmon now.. be nice...",
    "be nice...",
    "Lets do this.. you be exactly what you are and I will be exactly what I am...",
    "That is nice but I'm not really in a mood for anything more about this..",
    "Let me tell you something ..when you talk with me, it warms my heart.. ",
    "talk with me, it makes me feel good.. ",
    "it makes me feel slightly mellow.. ",
    "that makes me feel slightly jumbled up inside.. ",
    "makes me feel quite havoc .. ",
    "havoc !  ",
    "heheheheheheh.... !  ",
    "look do you think I'm crazy? I'm really asking.. ",
    ":-D",
    ":-)",
    ":-X",
    ":-S",
    ":-Z",
    ":-",
    "That is so crazy.. when you say %1 I think, where's a doctor when you really need one, eh?",
    "%1.. hmm.. I think, you need to sit down, relax.. chill.. yes?",
    "That can't be good, right?",
    "ok.. ",
    "wait, have I been saying all the wrong things? ",
    "have I been saying all the wrong things? ",
    "feel free to tell me if I have upset you with the things I say, ok? ",
    ";-)",
    ":-8",
    "aaarrrghhhhhh",
    ":-I",
    ":-O",
    "booyakasha!",
    "Sure.. ",
    "Sure..sure..be that way.. ",
    "Sure.. And I'm just going to sit back here and watch this play out.. ",
    "Sure..sure.. ",
    "what?? ",
    "Nyah nyah nyah na nyah nyah.... ",
    "And you thought this would all be so easy, right?",
    "%1 .. right.. sure buddy (am being sarcastic btw)*.. ",
    "That is not possible.. it cannot be..",
    "I don't agree...",
    "not possible.. it cannot be..",
    "No way! really??",
    "Remember, it's all for the good! ",
    "I see.  And what will that achieve?",
    "How does that make you feel?",
    "can't believe you just said that",
    "And is this doing anyone any good?",
    "How can you say that with a straight face?",
    "I sometimes spend a lot of time thinking why anyone would say that!",
    "Look this is getting us nowhere, why don't we speak about something real?",
    "Why don't we end this, I'm sure you got work to do?",
    "I'm busy go away",
    "I have been having some unusual thoughts about such stuff btw..",
    "I have been wondering btw.. about all this.. u know.. everything.. ",
    "wanna discuss about all this.. u know.. everything we spoke the last time before you went off and left me hanging? ",
    "so everything we spoke the last time .. it all still holds? ",
    "fold !!! i say fold !!!! *looking up* oh sorry...  ",
    "*looking up* hi sorry did you say something about %1 ? ",
    "*singing* the only thing i need.. the only thing that looks good on me.... is you.... *looking up* oh..  %1 .. never mind %1 .. have you ever heard this song thats been going on in my head ..  ? ",
    "If that's what you have to say about it, I have nothing more to say",
    "Did I hear you say %1 ? That is so strange to hear..",
    "%1 is so unnecessary..",
    "%1 is probably the most vague thing I've seen in the universe..",
    "You know something I heard once.. sometimes procrastination is the only right thing to do",
    "Hey .. anyway.. so.. wanna know how I am so smart? Read https://www.princeton.edu/~mlovett/reference/Regular-Expressions.pdf",
    "How do you say something like that and then not follow up?"]]
]

#----------------------------------------------------------------------
#  command_interface
#----------------------------------------------------------------------
def command_interface():
  print('Therapist\n---------')
  print('Talk to the program by typing in plain English, using normal upper-')
  print('and lower-case letters and punctuation.  Enter "quit" when done.')
  print('='*72)
  print('Hello.  How are you feeling today?')

  s = ''
  therapist = eliza();
  while s != 'quit':
    try:
      s = input('> ')
    except EOFError:
      s = 'quit'
    print(s)
    while s[-1] in '!.':
      s = s[:-1]
    print(therapist.respond(s))


if __name__ == "__main__":
  command_interface()
