questions = [
    ['Linux', 'Who wrote the Linux Kernel? 1 - Linus , 2 - Bill , 3 - Nikhil , 4 - Nobody', '1'],
    ['Linux', 'What file mounts a FS persistently? 1 - fstab , 2 - lvm.conf , 3 - multipath.conf , 4 - trin.conf', '1'],
    ['Indian culture', 'How many states in India?', '29'],
    ['Indian culture', 'Who wrote the national anthem of India?', 'Rabindranath Tagore'],
    ['Linux', 'Name of the penguin (Linux mascot)?', 'Tux'],
    ['Red Hat', 'Who is nkshirsa?', 'nikhil kshirsagar'],
    ['Red Hat', 'Where is Red Hat headquartered?', 'Raleigh'],
    ['Linux', 'What must you do during thinpool configuration? 1 - Pray 2 - Turn autoextend on 3 - Nothing 4 - Delete and use thick lvs', '2'],
    ['Linux', 'what command lists open files?', 'lsof'],
    ['Linux', 'what command shows kernel logs?', 'dmesg'],
    ['Linux', 'provides redundant paths to storage?', 'multipath'],
    ['Linux', 'http port?', '80'],
    ['Linux', 'https port?', '443'],
    ['Linux', '........ was the first feature film produced on Linux servers', 'titanic'],
    ['Linux', 'Linux for Drones , name of this OS?', 'dronecode'],
    ['Linux', 'what state of a process in ps output implies uninterruptible sleep?', 'D'],
    ['Linux', 'Command used to determine the path of an executable file is?', 'which'],
    ['Linux', 'What communication command provides communication to another user logged on by writing to the bottom of their terminal?', 'talk'],
    ['Linux', 'Which command will you use to see the available routes? 1 - show route 2 - route status 3 -  netstat -r 4 - none', '3'],
    ['Linux', 'Which of the following time stamps need not exist for a file on traditional unix file system? 1 - Access Time 2 - Modification Time 3 -  Creation Time 4 - Change Time', '3'],
    ['Linux', ' If a file is removed using rm then? 1 - The file can be recovered by a normal user 2 - The file cannot be recovered by a user 3 -  The file can be fully recovered provided the sytem is not rebooted 4 - The file will be moved to /lost+found directory and can be recovered only by administrators intervention', '2'],
    ['Red Hat Cee', 'Who developed foobar?', 'Madhavprasad Pai'],
    ['General Knowledge', 'Only constant according to einstein?', 'Speed of Light'],
    ['General Knowledge', 'Who wrote The Hitchhikers Guide to the Galaxy?', 'Douglas Adams'],
    ['General Knowledge','Number of bones in the adult human body?', '206'],
    ['General Knowledge','Largest planet in solar system?', 'Jupiter'],
    ['General Knowledge','Brightest object in night sky?', 'Venus'],
    ['General Knowledge','Brightest star?', 'Sirius'],
    ['General Knowledge','Closest star after the sun?', 'Alpha Centauri'],
    ['General Knowledge','nuclear plant that closed for ever in Ukrain?', 'Chernobyl'],
    ['General Knowledge',' scientific name of lie detector test used for proving lies?', 'Polygraph'],
    ['General Knowledge',' largest mammal?', 'blue whale'],
    ['General Knowledge',' largest land animal?', 'elephant'],
    ['General Knowledge',' longest river?', 'nile'],
    ['General Knowledge',' largest ocean?', 'pacific ocean'],
    ['General Knowledge',' most populated country?', 'china'],
    ['General Knowledge',' tallest building in the world?', 'burj khalifa'],
    ['General Knowledge',' largest freshwater lake in the world?', 'lake superior'],
    ['General Knowledge',' largest bird in the world?', 'ostrich'],
    ['General Knowledge',' planet with most number of moons (69 moons)?', 'jupiter'],
    ['General Knowledge',' farthest planet from sun in solar system?', 'pluto'],
    ['General Knowledge',' instrument used for recording intensity of earthquake shocks?', 'seismograph'],
    ['General Knowledge',' instrument used for measuring electric current?', 'galvanometer'],
    ['General Knowledge',' which country hosted 2016 olympic games?', 'brazil'],
    ['General Knowledge',' first country to launch a satellite in space?', 'russia'],
    ['General Knowledge',' first man to go to outer space?', 'yuri gagarin'],
    ['General Knowledge',' the space based satellite navigation system GPS stands for?', 'global positioning system'],
    ['General Knowledge',' Which planet has the feeling that sun rises in the west??', 'venus'],
    ['General Knowledge',' Ctrl, Shift and Alt are called ........ keys?', 'modifier'],
    ['General Knowledge','The working principle of a washing machine is? 1 - reverse osmosis 2 - diffusion 3 - centrifugation 4 - dialysis', '3'],
    ['General Knowledge','The blue colour of the clear sky is due to ........ of light ? 1 - Diffraction 2 - Dispersion 3 - Reflection 4 - Refraction', '2'],
    ['General Knowledge','Nuclear sizes are expressed in a unit named? 1 - Fermi 2 - Angstrom 3 - Newton 4 - Tesla', '1'],
    ['General Knowledge','Nuclear sizes are expressed in a unit named? 1 - Fermi 2 - Angstrom 3 - Newton 4 - Tesla', '1'],
    ['General Knowledge','Fastest spinning planet? 1 - Jupiter 2 - Earth 3 - Saturn 4 - Pluto', '1'],
    ['General Knowledge','Smallest planet? 1 - Mercury 2 - Earth 3 - Saturn 4 - Pluto', '1'],
    ['General Knowledge','Fastest planet? 1 - Mercury 2 - Earth 3 - Saturn 4 - Pluto', '1'],
    ['General Knowledge','FORTRAN is acronym for?', 'formula translator'],
    ['Linux', 'Which filesystem cannot be shrunk once created?', 'xfs'],
    ['Linux', 'Filesystem for CDROM is?', 'isofs'],
    ['Linux', 'This timer is decremented only when a process is executing?', 'ITIMER_VIRTUAL'],
    ['Linux', 'Daemon process is a? 1 - group leader 2 - session leader 3 - orphan process 4 - all of these', '4'],
    ['Linux', 'Which one of the following is not true about proc filesystem? 1 - proc filesystem is a pseudo-filesystem 2 - proc filesystem is used as an interface to kernel data structures 3 - some files in proc filesystem allow kernel variables to be changed 4 -  none of the mentioned', '4'],
    ['Linux', 'The file /proc/[PID]/maps contains the? 1 -  currently mapped memory regions 2 - available memory regions 3 - memory regions which are free to map 4 -  none of the mentioned ', '1'],
    ['Linux', 'Proc filesystem does not contain? 1 -  sub-directories for installed buses 2 - device files 3 - list of registered DMA 4 -  none of the mentioned ', '2'],
    ['Linux', 'Which one of the following operating system does not support proc filesystem?? 1 -  IBM AIX 2 - solaris 3 - HP UX 4 -  none of the mentioned ', '4'],
    ['Linux', 'The buddy algorithm handles the??', 'Memory fragmentation'],
    ['Linux', 'The major number identifies the _____ associated with the device.?', 'driver'],
    ['Linux', 'Function to get the parent process identification number?? 1 - waitpid()2 - getpid() 3 - getppid() 4 - parentid()', '3'],
    ['Linux', 'Fork returns _____ to parent process on success?? 1 - 0 2 - child process id  3 -  parent process id  4 - nothing', '2'],
    ['Linux', 'When mv f1 f2 is executed which files inode is freed?? 1 - f1 2 - f2 3 - none of these 4 - all of these', '2'],
    ['Linux', ' In linux, a device driver can work without ?? 1 -  major number 2 - minor number 3 - device file name 4 - none of these', '4'],
    ['Linux', 'Binary or executable files are:?? 1 - Regular files 2 - Device files 3 - Special files 4 - none of these', '1'],
    ['Linux', 'The terminal used by a Daemon process is? 1 - any terminal 2 - no terminal 3 -  root terminal 4 - serial port', '2'],
    ['Linux', 'Which of the following is not correct statement regarding file types?? 1 - Hard links share same inode number 2 -  Soft links cannot be created across partitions 3 - Socket files are Unix domain sockets 4 - Character file is a special file', '2'],
    ['Linux', 'Which is an example for character special file? 1 - Hard disk 2 - CDROM 3 - Terminal 4 - Memory', '3'],
    ['Linux', ' Which command is used to check filesystem usage in a system?? 1 - du 2 - df 3 - dd 4 - all of these ', '2'],
    ['Linux', ' Which among the following allows fast file system recovery??? 1 - Ext2 2 - Journaling 3 - Caching 4 - all of these', '2'],
    ['Linux', 'Linux threads implemented using what library?', 'pthreads'],
    ['Linux', 'What is used to analyze application dump files (core files)?', 'gdb'],
    ['Linux', 'What command is used to find the location of files??', 'locate'],
    ['Linux', 'What command is used to print the last few lines of a file??', 'tail'],
    ['Linux', 'What is LVM using for everything it does ?', 'Device mapper'],
    ['Red Hat trivia', 'What does SOL stand for in Red Hat?', 'Support Operations Lead'],
    ['General knowledge', 'Who said talk is cheap, show me the code', 'linus torvalds'],
    ['General knowledge', 'surely youre joking mr .......', 'feynman'],
    ['General knowledge', 'Lead singer of the doors ','jim morrison'],
    ['General knowledge', 'Second man on the moon?','buzz aldrin'],
    ['General knowledge', 'ali-g (and mine) favorite word??','booyakasha'],
    ['General knowledge', 'who plays borat??','sacha baron cohen'],
    ['General knowledge', 'dylan said - the answer my friend is..??','blowing in the wind'],
    ['General knowledge', 'Human body is sixty percent ..... ' , 'water'],
    ['General knowledge', 'Great writer of short stories, wrote most from prison' , 'O Henry'],
    ['General knowledge', 'Great writer of short stories, O Henry, his real name?' , 'William Sydney Porter'],
    ['General knowledge', 'Who wrote the screwtape letters (also wrote chronicles of narnia)?' , 'C S Lewis'],
    ['General knowledge', 'Great Indian classical flautist' , 'Hariprasad Chaurasia'],
    ['Red Hat', 'When was Red Hat established? (month year)', 'March 1993'],
    ['General knowledge', 'When did Red Hat go Public (year)', '1999'],
    ['Linux', 'Who designed the first PCP architecture?', 'Mark Goodwin'],
    ['General Knowledge', 'Who wrote A Brief History of Time?', 'Stephen hawking'],
    ['General Knowledge', 'Default IO scheduler on RHEL 7?', 'deadline'],
    ['General Knowledge', 'Default IO scheduler on RHEL 6?', 'cfq'],
    ['General Knowledge', 'Default filesystem on RHEL 6?', 'ext4'],
    ['General Knowledge', 'Default filesystem on RHEL 7?', 'xfs'],
    ['Linux', 'Where did the name GLUSTER come from?', 'GNU and Cluster'],
    ['Unix', 'Who wrote UNIX?', 'Dennis Ritchie'],
    ['Unix', 'Who created GPL license?', 'Richard Stallman'],
    ['Gaming', 'First ever video game made popular', 'pong'],
    ['Gaming', 'First ever graphical game written for PC in pascal by broderbund software', 'prince of persia'],
    ['Gaming', 'First popular strategy fantasy game', 'dungeons and dragons'],
    ['internet', 'popular text browser in the ninties', 'lynx'],
    ['linux', 'If one of the thread in multithreaded process is blocked on an I/O, which of the following is true? 1 - the entire process will block if their is no kernel supported threads 2 - Other threads of the process will continue to execute even if there is no kernel supported threads 3 - It depends on specific implementatation 4 - All of the mentioned', '1'],
    ['internet', 'popular search engine in the ninties', 'lycos'],
    ['internet', 'popular social media site before facebook ', 'orkut'],
    ['internet', 'First online bookstore', 'amazon'],
    ['gaming', 'First first person shooter game', 'wolfenstein'],
    ['internet', 'Popular search engine in the ninties before yahoo and google', 'altavista'],
    ['linux', 'This OS was what linus torvalds used to study before developing linux?', 'minix'],
    ['linux', 'Which niceness value among the following indicate most favorable scheduling? 1 - 0 , 2 - 19 , 3 - -20 , 4 - 100', '3'],
    ['linux', 'Each process has unique ? 1 - fd table , 2 -  file table, 3 -  inode table, 4 - data block table', '1'],
    ['linux', 'The file system information is stored in? 1 - Boot block, 2 - Super Block, 3 -  inode table, 4 - data block ', '2'],
    ['linux', 'What is the use of fcntl function?? 1 -  locking a file, 2 - reading the file descriptor flag, 3 -   changing the file status flag, 4 - all of the mentioned', '4'],
    ['linux', 'The maximum time slice that can be given to a process in Linux in ms? 1 - 10 , 2 - 50 , 3 - 200 , 4 - 600', '4'],
    ['linux', 'printf() uses which system call? 1 - open, 2 - read, 3 - write, 4 - none of these', '3'],
    ['linux', 'read() system call on success returns? 1 - 0, 2 - 1, 3 -  number of characters, 4 - none of these', '3'],
    ['linux', 'Default action of SIGSEGV is? 1 - Terminate, 2 - Core dump + Terminate, 3 -  Stop, 4 - none of these', '2'],
    ['linux', 'The persistancy of a FIFO is? 1 - process, 2 - kernel 3 -  file system , 4 - none of these', '3'],
    ['linux', 'Which one of the following is not system V IPC ?? 1 - Shared Memory, 2 - Semaphores 3 -  FIFO, 4 - Message Queues', '3'],
    ['linux', 'Command used to check shared memory is?? 1 - ipcs, 2 - ipcs -m 3 -  ipcs -s, 4 - ipcs -q', '2'],
    ['linux', 'Which is Fastest IPC??? 1 - Message Queue, 2 - shared memory 3 - Socket, 4 - FIFO', '2'],
    ['linux', 'A system has 512MB of physical memory. Which among the following is not a suitable virtual memory size for this system architecture?? 1 - 512MB, 2 - 256MB, 3 -4GB, 4 - none of these', '4'],
    ['linux', 'what is thin provisioning? 1 - redundant storage 2 - journalling filesystem 3 - multiple copies of storage like raid 4 - overallocation of storage', '4'],
    ['Linux', 'What helps monitor network traffic and activity?', 'tcpdump'],
    ['Linux', 'The structure which keeps the information about shared memory in the kernel?', 'shmid_ds'],
    ['Linux', 'Which call to use to set the resource count of semaphore??', 'sem_set_count'],
    ['Linux', ' Race condition can be avoided by using?? 1 - semaphore 2 - mutex 3 - both 4 - none', '3'],
    ['Linux', 'Linux kernel is?? 1 - Monolithic 2 - Microkernel 3 - Exo 4 - none', '1'],
    ['Linux', 'Section 2 of manpage describes?? 1 - Commands 2 - System calls 3 - Function calls 4 - Drivers', '2'],
    ['Linux', 'What helps find memory leaks in a program?', 'valgrind'],
    ['Linux', 'What tool from rational helps find root causes of crashes due to memory errors?', 'purify'],
    ['Linux', 'What tool from rational is a well known versioning system?', 'clearcase'],
    ['Linux', 'Who designed and developed git?', 'linus torvalds'],
    ['Linux', 'Name of Indian supercomputer running on linux?', 'param'],
    ['Linux', 'command to search for strings in text?', 'grep'],
    ['Linux', 'virtual devices created from existing disks which can be used for testing?', 'loopback devices'],
    ['Linux', 'What happens when debugger is attached to a running process ? 1 - process terminates 2 - process is paused 3 - all threads except main threads of process are suspended 4 - process continues running normally', '2'],
    ['Linux', 'What helps sync data from one disk or file to another across a network?', 'rsync'],
    ['Linux', 'What system call does malloc call?', 'brk'],
    ['Linux', 'How many passes does C compiler make? 1 - 1 , 2 - 2 , 3 - 3 , 4 - 10' , '2'],
    ['Linux', 'Can main be called from within main in c? 1 - always , 2 - never , 3 - sometimes , 4 - only with special gcc flag' , '1'],
    ['Linux', 'What C function helps make a copy of a process?', 'fork'],
    ['Linux', 'What library is automatically linked into your compiled C program?', 'standard library'],
    ['Linux', 'COFF is a ? 1 - network protocol 2 - file format 3 - debugger 4 - newly discovered asteroid', '2'],
    ['Linux', 'What did Steve Bourne write?', 'bash'],
    ['Linux', 'What is used to monitor system calls that a process makes?', 'strace'],
    ['Linux', 'What is the term for a function calling itself?', 'recursion'],
    ['C++', 'Hidden pointer stored for virtual functions in a class in C++?', 'vptr'],
    ['C++', 'vptr points to what for implementing virtual functions in a class in C++?', 'vtable'],
    ['C++', 'Who wrote c++?','Bjarne Stroustrup'],
    ['C programming', 'typedef in C is used for? 1 - defining macros 2 - writing new code 3 - making new types 4 - none of these','3'],
    ['C programming', 'break keyword in C is used for? 1 - calling interrupts 2 - dead code 3 - exitting the program 4 - none of these','4'],
    ['C programming', 'scanf in C is used for? 1 - calling interrupts 2 - input from user 3 - exitting the program 4 - none of these','2'],
    ['C programming', 'putc in C is used for? 1 - user input 2 - output to terminal 3 - exitting the program 4 - none of these','2'],
    ['C programming', '#pragma in C is used for? 1 - user input 2 - special switch for compiler 3 - exitting the program 4 - none of these','2'],
    ['C programming', 'system function in C is used for? 1 - calling interrupts 2 - invoking binaries 3 - exitting the program 4 - none of these','2'],
    ['C programming', 'Data structure that stores similar kinds of items in C?', 'array'],
    ['C programming', 'Data structure that stores dis-similar kinds of items in C?', 'struct'],
    ['C programming', 'In C which keyword skips certain an iteration of the loop and goes on to the next iteration?', 'continue'],
    ['C programming', 'In C which keyword chooses one block of statements from many based on a condition?', 'switch'],
    ['C programming', 'In C which keyword declares a variable or function has external linkage?', 'extern'],
    ['C programming', 'In C sizeof is a? 1 - function 2 - operator 3 - compiler directive 4 - none ', '2'],
    ['C programming', 'In C the fastest variables are created using this keyword', 'register'],
    ['C programming', 'using this keyword value of variables persist till end of the program', 'static'],
    ['C programming', 'in C this is used to associate a type with an identifier', 'typedef'],
    ['C programming', 'in C this is used to group different types of variables under a single name all sharing the same memory', 'union'],
    ['C programming', 'in C this keyword indicates a function does not return any value', 'void'],
    ['C programming', 'in C this keyword indicates a variable that can be modified in unspecified ways by hardware', 'volatile'],
    ['C programming', 'in C what function is used to allocate memory from the heap', 'malloc'],
    ['C programming', 'in C A variable declared in a function can be used in main() ? 1 - true 2 - false 3 - if static 4 - none' , '2'],
    ['C programming', 'in C Which among the following is NOT a logical or relational operator? ? 1 - != 2 - == 3 - || 4 - =' , '4'],
    ['C programming', 'in C Relational operators cannot be used on? ? 1 - structure  2 - long 3 - strings 4 - floats ' , '1'],
    ['C programming', 'in C When double is converted to float, then the value is?  1 - truncated 2 - rounded 3 - depends on the compiler 4 - depends on the standard' , '3'],
    ['C programming', 'in C Which type of conversion is NOT accepted?   1 - From char to int 2 - From float to char pointer 3 - From negative int to char 4 - From double to char' , '2'],
    ['C programming', 'in C Which of the following type-casting have chances for wrap around??   1 - From int to float 2 -  From int to char 3 - From char to short 4 - From char to int' , '2'],
    ['C programming', 'in C When do you need to use type-conversions??   1 - The value to be stored is beyond the max limit 2 -  The value to be stored is in a form not supported by that data type 3 - To reduce the memory in use, relevant to the value 4 - all of these' , '4'],
    ['C programming', 'in C The name of the variable used in one function cannot be used in another function ? 1 - true 2 - false 3 - maybe 4 - if declared static' , '2'],
    ['C programming', 'in C What is the type of the below assignment expression if x is of type float, y is of type int?? 1 - int 2 - float 3 - no type 4 - double' , '1'],
    ['C programming', 'for c = 2, value of c after c <<= 1; ? 1 - 1 2 - 2 3 - 3 4 - 4' , '4'],
    ['C programming', 'Which expression has to be present in the following exp1 ? exp2 : exp3;?  1 - exp1  2 - exp2 3 - exp3 4 - all ' , '4'],
    ['C programming', 'In expression i = g() + f(), first function called depends on?  1 - Compiler 2 - Associativiy of () operator 3 - Precedence of () and + operator 4 - left to write of expression' , '1'],
    ['C programming', 'Which of the following operators has an associativity from Right to Left? 1 - <= 2 - << 3 - == 4 - +=' , '4'],
    ['C programming', 'Comment on the following statement? n = 1;  printf("%d, %dn", 3*n, n++);? 1 - Output will be 3,2   2 - Output will be 3,1   3 - Output will be 6,1   4 - Output is compiler dependent ' , '4'],
    ['C programming', 'Which function in the following expression will be called first? 1 - func1()   2 - func2()   3 - func3()  4 - cannot be predicted' , '4'],
    ['C programming', 'Which of the following operator has the highest precedence in the following?? 1 - ()   2 - sizeof   3 - *  4 - +' , '1'],
    ['C programming', 'Which of the following operator is a ternary operator?? 1 - && 2 - >>= 3 - ?:  4 - ->' , '3'],
    ['C programming', 'Comment on the following statement? n = 1;  printf("%d, %dn", 3*n, n++);? 1 - <= 2 - << 3 - == 4 - +=' , '4'],
    ['C programming', 'in C Which of the following data type will throw an error on modulus operation(%)? 1 - char 2 - short 3 - int 4 - float ' , '4'],
    ['C programming', 'in C Result of a logical or relational expression in C is ? 1 - true or false 2 - 0 or 1 3 - 0 if an expression is false and any positive number if an expression is true 4 - none of these' , '2'],
    ['C programming', 'in C what are wild pointers? 1 - freed pointers 2 - uninitialized pointers 3 - allocated pointers 4 - pointers pointing to multiple things', '2'],
    ['C programming', 'in C which is not a valid variable name? 1 - int __a3 2 - int __3a 3 - int __A3 4 - none of these', '4'],
    ['C programming', 'in C which is not a valid variable name? 1 - int _a3 2 - int a_3  3 - int 3_a  4 - none of these', '3'],
    ['C programming', 'all keywords in C are? 1 - lowercase letters 2 - uppercase letters 3 - camelcase letters 4 - none of these', '1'],
    ['C programming', 'which cannot be a valid variable name in C? 1 - true 2 - volatile 3 - friend 4 - export', '2'],
    ['C programming', 'in C for printing data using printf the format identifier %d is used for? 1 - char 2 - int 3 - pointer 4 - none of these', '2'],
    ['C programming', 'in C what is the size of an int data type? 1 - 4 bytes 2 - 8 bytes 3 - depends on the system 4 - none of these', '3'],
    ['C programming', 'in C which data type has variable size? 1 - integer 2 - pointer 3 - struct 4 - double', '3'],
    ['C programming', 'in C 2. Which keyword is used to prevent any changes for a variable ? 1 - immutable 2 - mutable 3 - const 4 - volatile', '3'],
    ['C programming', 'in C enum data type is processed by the ? 1 - compiler 2 - preprocessor 3 - linker 4 - assembler', '1'],
    ['C programming', 'Which of these is false?? 1 - Constant variables need not be defined as they are declared and can be defined later 2 - Global constant variables are initialized to zero 3 -  const keyword is used to define constant values 4 -  You cannot reassign a value to a constant variable', '1'],
    ['C programming', 'Which of these is false?? 1 - A variable defined once can be defined again with different scope 2 - A single variable cannot be defined with two different types in the same scope 3 -  A variable must be declared and defined at the same time 4 -  A variable refers to a location in memory', '3'],
    ['C++ programming', 'in C++ what keyword is used to free allocated memory from the heap', 'delete'],
    ['C++ programming', 'in C++ what keyword is used to allocate memory from the heap', 'new'],
    ['linux', 'What is a context switch? 1 - Kernel switches from executing one process to another 2 - Process switches from kernel mode to user mode 3 - Process switches from user mode to kernel mode 4 - None of the mentioned', '1'],
    ['Linux', 'What state does a process go in when debugger attached to it? 1 - sleep 2 - tracing 3 - zombie 4 - no state change', '2'],
    ['Linux', 'What command is used to count the total number of lines, words, and characters contained in a file?', 'wc'],
    ['Linux', 'What hardware architecture is not supported by Red Hat?', 'Macintosh'],
    ['Linux', 'How do you find which remote hosts are connecting to your host on a particular port?', 'netstat'],
    ['Linux', 'What command helps find how many days your Server is up??', 'uptime'],
    ['Linux', 'What command helps find hostname from ip address?', 'nslookup'],
    ['Linux', 'Which well known text editor contains an inbuilt doctor or psychiatrist?', 'emacs'],
    ['Linux', 'Parent process id of a deamon process is? 1 - 2 ,  2 - 0 ,  3 - none of these  , 4 - 1', '4'],
    ['Linux', 'ctrl-c sends which signal?', 'sigint'],
    ['Linux', 'Which function returns two values at the same time?', 'fork'],
    ['Linux', 'ctrl-z sends which signal?', 'sigtstp'],
    ['Linux', 'NTP is used to synchronize what?', 'clock'],
    ['Linux', 'What is the default maximum number of processes that can exist in Linux? 1 - 32768 2 - 1024 3 - 4096 4 - no limit', '1'],
    ['Linux', 'What command will verify the syntax of a hosts.allow and hosts.deny file combination?', 'tcpdchk'],
    ['Linux', 'Worlds largest non-commercial Linux distribution?', 'Debian'],
    ['Linux', 'How do you define a macro in C? Using what keyword?', '#define'],
    ['Linux', 'How many bytes required to store an integer on x86_64?', '4'],
    ['Linux', 'How many bytes required to store a pointer on x86_64?', '8'],
    ['Linux', 'What are the arguments passed to a C main() function called by default?', 'argc and argv'],
    ['Linux', 'What program is used to analyze a vmcore?', 'crash'],
    ['Linux', 'What is the name of our internal cee vmcore analysis server?', 'optimus'],
    ['Linux', 'What is the name of the command to build an rpm package?', 'rpmbuild'],
    ['Linux', 'What is the tool to autodownload case attachments?', 'foobar'],
    ['Linux', 'What is the tool to auto analyze sosreports for problems?', 'insights'],
    ['Linux', 'What is the tool to analyze problems related to storage performance?', 'iostat'],
    ['Linux', 'What command loads a driver at runtime?', 'modprobe'],
    ['Linux', 'This company makes device drivers for video cards, and a lot more?', 'nvidia'],
    ['Linux', 'This company tried to make their own version of linux and failed miserably?', 'oracle'],
    ['Linux', 'What is a good network protocol for audio and video?', 'UDP'],
    ['Linux', 'Microsoft cloud solution?', 'azure'],
    ['Linux', 'Red Hat cluster solution for rhel 7 ?', 'pacemaker'],
    ['Linux', 'Which of the following protocols/tools is MOST likely to be used in integrating a Linux system into a Windows network, and for accessing Windows files?', 'Samba'],
    ['General Knowledge', 'Great computer scientist, famous for his computer science concepts called machines?', 'Alan Turing'],
    ['General Knowledge', 'Great computer scientist, wrote a great book on operating systems?', 'Andrew Tannenbaum'],
    ['General Knowledge', 'What bot do I fear the most?', 'redskull'],
    ['General Knowledge', 'What do bots do when they cannot sleep?', 'count electric sheep'],
    ['General Knowledge', 'The best AI chat bot in the world?', 'quizbot'],
    ['General Knowledge', 'CEO of google, an Indian...', 'Sundar Pichai'],
    ['General Knowledge', 'What is my favorite hobby?', 'shayari'],
    ['Linux', 'First alpha release of linux in which month and year', 'January 1996'],
    ['Linux', 'Full form of l10n', 'localization'],
    ['Linux', 'Full form of i18n', 'internationalization'],
    ['Linux', 'Largest contributor to Linux Kernel?', 'Intel'],
    ['General Knowledge', 'Best selling Indian author won the Man Booker Prize for Fiction?', 'Arundhati Roy'],
    ['General Knowledge', 'Who wrote A song of Fire and Ice on which is based Game of Thrones?', 'George R. R. Martin'],
    ['General Knowledge', 'How wicked am I?', 'So wicked that this answer is something nobody can guess and so just give up already!'],
    ['Linux', 'Which command displays the list of groups to which a user belongs?', 'lsgroup'],
    ['Linux', 'EMC multipathing solution?', 'powerpath'],
    ['Linux', 'Storage protocol that completely bypasses scsi ?', 'nvme'],
    ['Linux', 'What is infiniband?', 'networking protocol'],
    ['Linux', 'used in programming to synchronize threads of a process in order to protect global data access?', 'mutex'],
    ['Linux', 'What service is used to configure and capture a vmcore?', 'kdump'],
    ['Linux', 'What does kdump internally use?', 'kexec'],
    ['Linux', 'daemon that lvm currently uses, deprecated in RHEL 8?', 'lvmetad'],
    ['Linux', 'Which filesystem supports filesystem level snapshots?', 'btrfs'],
    ['Linux', 'Name of virtual filesystem that stores process information in memory? (starts with /)', '/proc'],
    ['Linux', 'Name of encryption module used by Red Hat?', 'luks'],
    ['Linux', 'Command to manually reclaim space from SSD storage after data deleted from filesystem?', 'fstrim'],
    ['Red Hat', 'Our biggest competitor?', 'Suse'],
    ['Red Hat', 'Red Hats acquisition for kubernetes development?', 'CoreOS'],
    ['Linux', 'What must you install for getting symbols in application core files? 1 - debuginfo packages, 2 - strace , 3 - kdump , 4 - sym drivers', '1'],
    ['Linux', 'What is the command to display a backtrace in a vmcore? 1 - show, 2 - log, 3 - bt, 4 - goto', '3'],
    ['Linux', 'What is the smallest size of IO in a RHEL system? 1 - blocksize, 2 - chunksize, 3 - minimum_io_size, 4 - kblockd', '3'],
    ['me', 'On a scale of 1 to 10, how enthusiastic are folks about me? 1 - 1, 2 - 2, 3 - 5, 4 - 10', '1'],
    ['me', 'What language am I written in?', 'python'],
    ['Linux', 'Which key combination can yank a line in vi? 1 - yw, 2 - dd, 3 - yy, 4 - dy', '3'],
    ['Linux', 'Choose the correct from below to search for lines beginning with the pattern using grep 1 - ^pattern, 2 - pattern^, 3 -  $pattern, 4 - none of these', '1'],
    ['Linux', 'Which command can be used to make variables of shell to be made available to sub shell? 1 - import, 2 - export, 3 -  echo, 4 - none of these', '2'],
    ['Linux', 'The command mknod myfifo b 4 16 will create what? 1 - a block device if user is root, 2 - a block device for all users, 3 -  a FIFO if user is not root, 4 - none of these', '1'],
    ['Linux', 'Which command is used to record a user login session in a file? 1 - macro, 2 - read, 3 - history, 4 - script', '4'],
    ['General Knowledge', 'WiFi full form?', 'Wireless Fidelity'],
    ['Linux', 'What does LUKS do?', 'encryption'],
    ['Linux', 'What has the sole purpose of helping mount the root filesystem', 'initramfs'],
    ['Linux', 'Which daemon tracks events on your system?', 'syslogd'],
    ['Linux', 'Filesystem data structure which has the description of all the files and pointers to the data blocks of files stored in it?', 'inode'],
    ['Linux', 'Which command is used to check the number of files and disk space used and the each users defined quota?', 'repquota'],
    ['Linux', 'Which utility is used automate rotation of logs?', 'logrotate'],
    ['Linux', 'Which daemon is used for scheduling of the commands?', 'crond'],
    ['Linux', 'Linux kernel feature that allows to aggregate multiple network interfaces into a single virtual link?', 'Network Bonding'],
    ['Linux', 'A process is said to be in this state when it has finished execution but is waiting for its parent to retrieve its exit status?', 'zombie'],
    ['Linux', 'What will help list the services that are enabled at a particular run level in linux server ??', 'chkconfig'],
    ['Linux', 'What script is used to rescan scsi devices?', 'rescan-scsi-bus.sh'],
    ['Linux', 'In Puppet what are the files in which the client configuration is specified called?', 'manifests'],
    ['Linux', 'the average sum of the number of process waiting in the run queue?', 'load average'],
    ['Linux', 'Which files stores the user min UID, max UID, password expiration settings, password encryption method being used etc?', 'login.defs'],
    ['Linux', 'What is /etc/skel used for? 1 - copy file to new user account automatically 2 - define network topology 3 - kill particular processes 4 - none of these', '1'],
    ['Linux', 'What does echo $? do? 1 - current shell ID 2 - prints the arguments passed 3 - shows the exit status of the most previous process command  4 - none of these', '3'],
    ['Linux', 'What does echo $$ do? 1 - report PID of previous background process 2 - shows current shell ID 3 - shows the exit status of the most previous process command  4 - none of these', '2'],
    ['Linux', 'What does echo $@ do? 1 - report PID of previous background process 2 - shows current shell ID 3 - shows the exit status of the most previous process command  4 - none of these', '4'],
    ['Linux', 'What does echo $# do? 1 - report PID of previous background process 2 - shows total number of arguments passed ID 3 - shows the exit status of the most previous process command  4 - none of these', '2'],
    ['Linux', 'What does echo $! do? 1 - report PID of previous background process 2 - shows total number of arguments passed ID 3 - shows the exit status of the most previous process command  4 - none of these', '1'],
    ['Linux', 'What does echo $* do? 1 - report PID of previous background process 2 - shows total number of arguments passed ID 3 - prints arguments passed 4 - none of these', '3'],
    ['Linux', 'Command and flag used to convert ext2 file system into ext3?', 'tune2fs -j'],
    ['Linux', 'Last field of fstab is for? 1 - device 2 - filesystem type 3 - filesystem check 4 - none of these', '3'],
    ['Linux', 'In filesystems Maximum mount count is for? 1 - How many times can it be mounted 2 - after how many mounts to run fsck 3 - How many concurrent mounts 4 - none of these', '2'],
    ['Linux', ' To increase the response time and throughput, the kernel minimizes the frequency of disk access by keeping a pool of internal data buffer called? 1 - Pooling 2 - Spooling 3 - Buffer cache 4 - Swapping ', '3'],
    ['Linux', 'At start of process execution, STDOUT & STDERR 1- Point to current terminal device 2 - Are closed 3 -  Point to special files on the system 4 - None of the mentioned ', '1'],
    ['Linux', 'wtmp and utmp files contain 1 - Temporary system data 2 - User login-logout log 3 - The users command execution log 4 - The users su and sudo attempts', '2'],
    ['Linux', 'Applications communicate with kernel by using:', 'System calls'],
    ['Linux', 'command to run to move all data to other PVs before you can safely remove a PV from a VG', 'pvmove'],
    ['Linux', 'command used to configure the kernel-resident network interfaces', 'ifconfig'],
    ['Linux', 'Displays a list of all recently used commands', 'history'],
    ['Linux', 'Changes the date accessed or date modified of the given file to right now.', 'touch'],
    ['Linux', 'Downloads the file or page at the given web URL', 'wget'],
    ['Linux', 'Displays the current user name', 'whoami'],
    ['Linux', 'combination of ping and traceroute command.', 'mtr'],
    ['Linux', 'Prints running processes with child processes, recursively.', 'pstree'],
    ['Linux', 'A ..... before a bash command, is not recorded in history.', 'space'],
    ['Linux', 'Detach and Reattach, long running process from a session.', 'screen'],
    ['Linux', 'Shows all the shortcuts available in Bash.', 'bind -p'],
    ['Linux', 'This command creates another new X session.', 'startx'],
    ['Linux', 'Which of the following is NOT a UNIX variant ? 1 - solaris 2 - aix 3 - irix 4 - as400', '4'],
    ['Linux', 'The system calls in Linux are written using which language 1 - C 2 - C++ 3 - python 4 - perl', '1'],
    ['Linux', 'Which command is used to set limits on file size', 'ulimit'],
    ['Linux', 'How many links are created when we creat a directory file?', '2'],
    ['Linux', 'If two files on same partition point to the same inode structure they are called', 'hard links'],
    ['Linux', 'Where can I find the printer in the file structure? 1 - /etc 2 - /dev 3 - /lib 4 - printer', '2'],
    ['Linux', 'Which of the following statement is true? 1 - The cp command will preserve the meta data of the file 2 - The sort command by default sorts in the numeric order 3 - The mv command will preserve the meta data of the file 4 - The command ps will display the filesystem usage', '3'],
    ['Linux', 'What UNIX command is used to update the modification time of a file? 1 - time 2 - modify 3 - touch 4 - none of these', '3'],
    ['Linux', 'Which of the following is not a valid run-level 1 - S 2 - 0 3 - 8 4 - 1', '3'],
    ['Linux', 'The shell used for Single user mode shell is 1 - bash 2 - csh 3 - ksh 4 - sh', '4'],
    ['Linux', 'Which is the only partition mounted in Single user mode 1 - boot 2- usr 3 - root  4 - tmp', '3'],
    ['Linux', 'At the end of kernel bootstrap, which process is started?', 'init'],
    ['Linux', 'Which file is read by init to get the default runlevel', 'inittab'],
    ['Linux', 'Which of the following statement is FALSE ? 1 - Unix supports multiple users 2 - Linux is an open source operating system and the source code is shared 3 - Shell takes care of inter process communication 4 - Shell provides the feature of I/O Redirection', '3'],
    ['Linux', ' If a program executing in background attempts to read from STDIN 1 - It is terminated 2 - Its execution is suspended 3 - STDIN is made available to it 4 - None of the mentioned', '2'],
    ['Linux', 'When a child process exits before the parent process exits, which of the following is true: 1 -  the child process becomes defunct 2 -  the parent process becomes defunct 3 -  if the parent process does not handle SIGCHLD, the child process becomes a zombie 4 - none of the mentioned', '3'],
    ['Linux', 'srwxr-xrw- is a 1 - internet socket file 2 -  unix domain socket file 3 - symbolic link 4 - shared file', '3'],
    ['Linux', 'Which of the following is not a valid file type on Linux 1 - Socket 2 - Softlink 3 - Inode 4 - FIFO', '3'],
    ['Linux', 'Which are the two types of device files? 1 - Character & Block 2 - Character & Socket 3 - Block & FIFO 4 - Input & output', '1'],
    ['Linux', 'The encrypted password of a user is stored in 1 - /etc/shadow 2 - /etc/enpasswwd 3 - /etc/.passwd 4 - /etc/passwd', '1'],
    ['Linux', 'User id 0 is 1 - An invalid user id 2 - The id of the root user 3 - The id of a user when the users account is deleted 4 - None of the mentioned ', '2'],
    ['Linux', 'By default, a Linux user falls under which group? 1 - staff 2 - others 3 - same as userid 4 - system', '3'],
    ['Linux', 'What will be output of following command: $ echo "The process id is" $$$$ 1 - The process id is $$ 2 - The process id is $<pid>$<pid> 3 - The process id is <pid><pid> 4 - The process id is $$$$', '3'],
    ['Linux', 'The file permission 764 means: 1 - Every one can read, group can execute only and the owner can read and write 2 - Every one can read and write, but owner alone can execute 3 - Every one can read, group including owner can write, owner alone can execute 4 - Every one can read and write and execute', '3'],
    ['Linux', 'Sticky bit can be set using following permission 1 - 0777 2 - 2666 3 - 4744 4 - 1711', '4'],
    ['Linux', 'A user does a chmod operation on a file. Which of the following is true? 1 - The last accessed time of the file is updated 2 - The last modification time of the file is updated 3 - The last change time of the file is updated 4 - None of the mentioned', '3'],
    ['Linux', 'If the umask value is 0002. what will be the permissions of new directory 1 - 777 2 - 775 3 - 774 4 - 664', '2'],
    ['Linux', 'What does chmod +t do? 1 - wrong syntax 2 - set effective userid for filename 3 - set effective groupid for filename 4 - set the sticky bit', '4'],
    ['Linux', 'Which of the following umask settings doesnt allow execute permission to be set by default on directory files 1 - 222 2 - 111 3 - 000 4 - 444', '3'],
    ['Linux', ' While executing a command, the shell 1 - Executes it in the same process (as shell) 2 - Creates a child shell to execute it 3 - Loads a special program to take care of the execution 4 - None of the mentioned', '2'],
    ['Linux', 'Which command is used to debug a shell script program 1 - set 2 - set -x 3 - debug 4 - db', '2'],
    ['Linux', 'For every successful login, which script will be executed? 1 - /etc/inittab 2 - /etc/profile 3 - /etc/login 4 - /etc/init', '2'],
    ['Linux', ' Which of the following is true? 1 - Shell is a process and can be started by superuser only 2 - Shell is a built-in Kernel functionality 3 - Shell is a wrapper for all the commands and utilities 4 - None of the mentioned', '3'],
    ['Linux', 'BASH shell stands for? 1 - Bourne-again Shell 2 - Basic Access Shell 3 - Basic to Advanced Shell 4 - Big & Advanced Shell ', '1'],
    ['Linux', 'The redirection 2> abc implies 1 - Write file 2 to file abc 2 - Write standard output to abc 3 -  Write standard error to abc 4 -  None of the mentioned ', '3'],
    ['Linux', 'cmd 2>&1 > abc will 1 - Write file2 to file1 2 - Write standard output and standard error to abc 3 - Write standard error to abc 4 - Write standard output to abc & standard error to monitor', '4'],
]
